from raspechatka.deletion import is_external_event_suppressed
from __future__ import annotations

import calendar

import frappe
from frappe import _
from frappe.utils import add_days, flt, get_datetime, getdate, now, now_datetime, nowdate

from raspechatka.access_contract import access_contract
from raspechatka.pos_settings import get_pos_sales_rules, get_pos_sales_settings
from raspechatka.pricing import resolve_point_price
from raspechatka.time_contract import (
	get_effective_site_timezone,
	legacy_external_instant_to_site_naive,
	resolve_point_timezone,
	site_naive_to_utc_rfc3339,
)

_POS_INSTANT_FIELDS = (
	"createdAt",
	"openedAt",
	"closedAt",
	"postingDatetime",
	"dueAt",
	"readyAt",
	"issuedAt",
	"countedAt",
)


def _legacy_pos_site_datetime(value):
	return legacy_external_instant_to_site_naive(value, get_effective_site_timezone())


def _normalize_legacy_payload(payload):
	normalized = dict(payload or {})
	for field in _POS_INSTANT_FIELDS:
		if normalized.get(field):
			normalized[field] = _legacy_pos_site_datetime(normalized[field])
	return normalized


def _pos_datetime_to_utc(value):
	if not value:
		return None
	return site_naive_to_utc_rfc3339(get_datetime(value), get_effective_site_timezone())


@frappe.whitelist()
@access_contract(auth="current_user", action="read", scope="point")
def get_bootstrap(workplace_code=None):
	"""Return the cashier, point rules and point-specific catalog for POS."""
	if frappe.session.user == "Guest":
		frappe.throw("Требуется авторизация", frappe.AuthenticationError)

	employee = _get_employee()
	allowed_points = _employee_points(employee)
	workplace = _get_workplace(workplace_code, allowed_points)
	point = frappe.get_doc("Business Point", workplace.business_point)

	return {
		"employee": {
			"id": employee.get("name"),
			"name": employee.get("employee_name") or frappe.session.user,
		},
		"point": {
			"id": point.name,
			"name": point.point_name,
			"timezone": resolve_point_timezone(point.timezone, get_effective_site_timezone()),
		},
		"workplace": {"id": workplace.name, "name": workplace.workplace_name},
		"rules": get_pos_sales_rules(),
		"products": _get_products(point.name),
		"customers": _get_customers(),
		"workplaceData": _get_workplace_data(employee, point, workplace),
	}


@frappe.whitelist(methods=["POST"])
@access_contract(auth="current_user", action="create", scope="point")
def push_events(workplace_code: str | None = None, events: str | list | None = None):
	"""Accept the local POS outbox idempotently.

	The event_id is generated by the workstation and is unique. Re-sending the
	same batch after a network interruption therefore never duplicates a sale.
	"""
	if frappe.session.user == "Guest":
		frappe.throw("Требуется авторизация", frappe.AuthenticationError)

	events = frappe.parse_json(events) if isinstance(events, str) else (events or [])
	if not isinstance(events, list):
		frappe.throw("Ожидается список событий")
	if len(events) > 100:
		frappe.throw("За один запрос можно передать не более 100 событий")  # noqa: RUF001

	employee = _get_employee()
	workplace = _get_workplace(workplace_code, _employee_points(employee))
	accepted = []
	for event in events:
		event_id = str(event.get("id") or "").strip()
		event_type = str(event.get("eventType") or "").strip()
		event_payload = _normalize_legacy_payload(event.get("payload") or {})
		if not event_id or not event_type:
			frappe.throw("В событии отсутствует id или eventType")  # noqa: RUF001
		if not frappe.db.exists("POS Event", event_id):
			frappe.get_doc(
				{
					"doctype": "POS Event",
					"event_id": event_id,
					"event_type": event_type,
					"business_point": workplace.business_point,
					"pos_workplace": workplace.name,
					"cashier_user": frappe.session.user,
					"occurred_at": _legacy_pos_site_datetime(event.get("createdAt"))
					if event.get("createdAt")
					else now(),
					"payload_json": frappe.as_json(event_payload, indent=2),
					"received_at": now(),
				}
			).insert(ignore_permissions=True)
			_apply_pos_event(event_type, event_id, workplace, event_payload)
		accepted.append(event_id)

	return {"accepted": accepted}


def _get_employee():
	rows = frappe.get_all(
		"Employee",
		filters={"user": frappe.session.user, "active": 1},
		fields=["name", "employee_name"],
		limit_page_length=1,
	)
	if rows:
		return rows[0]
	if frappe.session.user == "Administrator":
		return frappe._dict(name="Administrator", employee_name="Администратор")
	frappe.throw("Для пользователя не создан активный сотрудник", frappe.PermissionError)


def _employee_points(employee):
	if employee.name == "Administrator":
		return frappe.get_all("Business Point", filters={"active": 1}, pluck="name")
	return frappe.get_all(
		"Employee Point Assignment",
		filters={"parent": employee.name, "parenttype": "Employee"},
		pluck="business_point",
	)


def _get_workplace(workplace_code, allowed_points):
	filters = {"active": 1, "business_point": ["in", allowed_points or ["__none__"]]}
	if workplace_code:
		filters["workplace_code"] = workplace_code
	rows = frappe.get_all(
		"POS Workplace",
		filters=filters,
		fields=["name", "workplace_name", "workplace_code", "business_point"],
		order_by="workplace_name asc",
		limit_page_length=2,
	)
	if not rows:
		frappe.throw("Для доступной точки не настроено рабочее место кассы")
	if not workplace_code and len(rows) > 1:
		frappe.throw("Укажите код рабочего места: пользователю доступно несколько касс")
	return rows[0]


def _get_products(point_name):
	today = getdate(nowdate())
	assortments = frappe.get_all(
		"Catalog Assortment",
		filters={"business_point": point_name, "enabled": 1},
		fields=["item", "valid_from", "valid_upto"],
		limit_page_length=5000,
	)
	assortments = [
		row
		for row in assortments
		if (not row.valid_from or getdate(row.valid_from) <= today)
		and (not row.valid_upto or getdate(row.valid_upto) >= today)
	]
	if not assortments:
		return []

	warehouse = frappe.db.get_value("Catalog Warehouse", {"business_point": point_name, "active": 1}, "name")
	balances = (
		{
			row.item: flt(row.actual_qty)
			for row in frappe.get_all(
				"Stock Balance",
				filters={"warehouse": warehouse},
				fields=["item", "actual_qty"],
				limit_page_length=0,
			)
		}
		if warehouse
		else {}
	)
	storage = {
		row.item: row.full_address
		for row in frappe.get_all(
			"Catalog Item Storage",
			filters={"warehouse": warehouse, "active": 1} if warehouse else {"name": "__none__"},
			fields=["item", "full_address"],
			limit_page_length=5000,
		)
	}
	items = {
		row.name: row
		for row in frappe.get_all(
			"Catalog Item",
			filters={"name": ["in", [row.item for row in assortments]], "active": 1},
			fields=[
				"name",
				"item_name",
				"item_code",
				"item_type",
				"catalog_group",
				"stock_uom",
				"track_inventory",
				"prevent_discounts",
				"has_variants",
			],
			limit_page_length=5000,
		)
	}
	group_names = {
		row.name: row.group_name
		for row in frappe.get_all(
			"Catalog Group",
			filters={
				"name": [
					"in",
					list({row.catalog_group for row in items.values() if row.catalog_group}) or ["__none__"],
				]
			},
			fields=["name", "group_name"],
			limit_page_length=1000,
		)
	}
	result = []
	for assortment in assortments:
		item = items.get(assortment.item)
		if not item or item.has_variants:
			continue
		resolved_price = resolve_point_price(
			item.name,
			point_name,
			required=False,
		)
		if not resolved_price and not get_pos_sales_settings()["allow_free_price"]:
			continue
		price = resolved_price["rate"] if resolved_price else 0
		barcode = frappe.db.get_value(
			"Catalog Item Barcode",
			{"parent": item.name, "parenttype": "Catalog Item", "parentfield": "barcodes"},
			"barcode",
		)
		result.append(
			{
				"id": item.name,
				"name": item.item_name,
				"sku": item.item_code,
				"category": group_names.get(item.catalog_group) or "Без группы",
				"type": {
					"Product": "product",
					"Variant": "product",
					"Service": "service",
					"Bundle": "bundle",
				}.get(item.item_type, "service"),
				"uom": item.stock_uom or "шт",
				"priceMinor": round(price * 100),
				"barcode": barcode,
				"stock": flt(balances.get(item.name)) if item.track_inventory else None,
				"trackInventory": bool(item.track_inventory),
				"allowNegativeStock": False,
				"minimumSalePriceMinor": 0,
				"preventDiscounts": bool(item.prevent_discounts),
				"storageAddress": storage.get(item.name) or "",
			}
		)
	return sorted(result, key=lambda row: (row["category"], row["name"]))


def _get_operational_catalog(point_name):
	"""Return active leaf catalog items with point warehouse facts, independent of sale assortment."""
	warehouse = frappe.db.get_value(
		"Catalog Warehouse",
		{"business_point": point_name, "active": 1},
		"name",
	)
	balances = (
		{
			row.item: flt(row.actual_qty)
			for row in frappe.get_all(
				"Stock Balance",
				filters={"warehouse": warehouse},
				fields=["item", "actual_qty"],
				limit_page_length=0,
			)
		}
		if warehouse
		else {}
	)
	storage = (
		{
			row.item: row.full_address
			for row in frappe.get_all(
				"Catalog Item Storage",
				filters={"warehouse": warehouse, "active": 1},
				fields=["item", "full_address"],
				limit_page_length=5000,
			)
		}
		if warehouse
		else {}
	)
	rows = frappe.get_all(
		"Catalog Item",
		filters={"active": 1},
		fields=[
			"name",
			"item_name",
			"item_code",
			"item_type",
			"stock_uom",
			"track_inventory",
			"has_variants",
		],
		order_by="item_name asc",
		limit_page_length=0,
	)
	result = []
	for row in rows:
		# A Product template with variants is not an operational leaf. Variants,
		# simple Products, Services and Bundles remain selectable for point needs.
		if row.item_type == "Product" and row.has_variants:
			continue
		result.append(
			{
				"id": row.name,
				"name": row.item_name,
				"itemCode": row.item_code or "",
				"itemType": row.item_type,
				"uom": row.stock_uom or "шт",
				"trackInventory": bool(row.track_inventory),
				"stock": flt(balances.get(row.name)) if row.track_inventory else None,
				"storageAddress": storage.get(row.name) or "",
			}
		)
	return result


def _get_customers():
	purchases = {
		row.client: row
		for row in frappe.get_all(
			"Client Purchase",
			fields=[
				"client",
				"count(name) as purchase_count",
				"sum(net_amount - returned_amount) as total_spent",
			],
			group_by="client",
			limit_page_length=10000,
		)
	}
	return [
		{
			"id": row.name,
			"name": row.client_name,
			"phone": row.phone,
			"discountPercent": flt(row.discount_percent),
			"purchaseCount": int((purchases.get(row.name) or {}).get("purchase_count") or 0),
			"totalSpentMinor": round(flt((purchases.get(row.name) or {}).get("total_spent")) * 100),
		}
		for row in frappe.get_all(
			"Client",
			filters={"active": 1},
			fields=["name", "client_name", "phone", "discount_percent"],
			order_by="client_name asc",
			limit_page_length=10000,
		)
	]


def _apply_pos_event(event_type, event_id, workplace, payload):
	payload = _normalize_legacy_payload(payload)
	if event_type in ("sale.completed", "sale.returned") and is_external_event_suppressed("POS", payload.get("id")):
		return
	if event_type == "sale.completed":
		_apply_sale(event_id, workplace, payload)
	elif event_type == "sale.returned":
		_apply_return(event_id, workplace, payload)
	elif event_type == "stock.write_off.requested":
		_apply_stock_write_off(event_id, workplace, payload)
	elif event_type == "point.supply.requested":
		_apply_supply_request(event_id, workplace, payload)
	elif event_type == "cleaner.visit.recorded":
		_apply_cleaner_visit(event_id, workplace, payload)
	elif event_type == "cleaner.paid":
		_apply_cleaner_payment(event_id, workplace, payload)
	elif event_type == "cash.counted":
		_apply_cash_count(event_id, workplace, payload)
	elif event_type == "order.created":
		_apply_order_created(event_id, workplace, payload)
	elif event_type == "order.updated":
		_apply_order_updated(event_id, workplace, payload)


def _order_source_receipt(point_name, source_sale_id):
	source_sale_id = str(source_sale_id or "").strip()
	if not source_sale_id:
		return None
	if source_sale_id.startswith("server:"):
		name = source_sale_id.removeprefix("server:")
		return frappe.db.get_value(
			"Sales Receipt",
			{"name": name, "business_point": point_name, "receipt_type": "Sale"},
			"name",
		)
	return frappe.db.get_value(
		"Sales Receipt",
		{"business_point": point_name, "external_id": source_sale_id, "receipt_type": "Sale"},
		"name",
	)


def _apply_order_created(event_id, workplace, payload):
	if not _doctype_exists("POS Order"):
		frappe.throw("POS Order недоступен для синхронизации")
	existing_point = frappe.db.get_value("POS Order", {"source_pos_event": event_id}, "business_point")
	if existing_point:
		if existing_point != workplace.business_point:
			frappe.throw(_("Событие заказа принадлежит другой точке"), frappe.PermissionError)
		return
	# Serialize number allocation per point. The technical order_number remains
	# the immutable lookup key for queued order.updated events.
	frappe.db.sql("select name from `tabBusiness Point` where name=%s for update", workplace.business_point)
	customer_number = str(payload.get("customerOrderNumber") or "").strip()
	if not customer_number:
		customer_number = _allocate_customer_order_number(workplace.business_point, payload.get("phone"))
	elif frappe.db.exists(
		"POS Order",
		{
			"business_point": workplace.business_point,
			"customer_order_number": customer_number,
			"status": ["in", ["New", "In Progress", "Ready"]],
		},
	):
		frappe.throw(_("Номер заказа для клиента уже занят на этой точке"))
	status = {
		"new": "New",
		"in_progress": "In Progress",
		"ready": "Ready",
		"issued": "Issued",
		"cancelled": "Cancelled",
	}.get(payload.get("status"), "New")
	source_sale_id = str(payload.get("sourceSaleId") or "").strip() or None
	source_receipt = _order_source_receipt(workplace.business_point, source_sale_id)
	doc = frappe.get_doc(
		{
			"doctype": "POS Order",
			"order_number": payload.get("orderNumber"),
			"customer_order_number": customer_number,
			"phone": payload.get("phone"),
			"contact_method": payload.get("contactMethod") or None,
			"customer_name": payload.get("customerName"),
			"business_point": workplace.business_point,
			"source_pos_event": event_id,
			"last_pos_update_at": payload.get("updatedAt") or None,
			"source_sale_id": source_sale_id,
			"fiscal_number": payload.get("fiscalNumber"),
			"total_amount": flt(payload.get("totalMinor")) / 100,
			"paid_amount": flt(payload.get("paidMinor")) / 100,
			"status": status,
			"comment": payload.get("comment"),
			"due_at": payload.get("dueAt"),
			"created_at": payload.get("createdAt") or None,
			"ready_at": payload.get("readyAt") or None,
			"issued_at": payload.get("issuedAt") or None,
			"source_receipt": source_receipt,
			"items": [
				{
					"item": x.get("productId")
					if frappe.db.exists("Catalog Item", x.get("productId"))
					else None,
					"item_name": x.get("name"),
					"quantity": flt(x.get("quantity")),
					"rate": flt(x.get("unitPriceMinor")) / 100,
					"amount": flt(x.get("quantity")) * flt(x.get("unitPriceMinor")) / 100,
				}
				for x in payload.get("lines", [])
			],
		}
	)
	doc.insert(ignore_permissions=True)


def _allocate_customer_order_number(point_name, phone):
	base = "".join(ch for ch in str(phone or "") if ch.isdigit())[-4:].zfill(4)
	used = {
		row[0]
		for row in frappe.db.sql(
			"""select customer_order_number from `tabPOS Order`
			where business_point=%s and status in ('New','In Progress','Ready')
			and customer_order_number is not null""",
			point_name,
		)
	}
	suffix = 0
	while (f"{base} ({suffix})" if suffix else base) in used:
		suffix += 1
	return f"{base} ({suffix})" if suffix else base


def _apply_order_updated(event_id, workplace, payload):
	if not _doctype_exists("POS Order"):
		frappe.throw("POS Order недоступен для синхронизации")
	name = frappe.db.get_value(
		"POS Order",
		{
			"order_number": payload.get("orderNumber"),
			"business_point": workplace.business_point,
		},
		"name",
	)
	if not name:
		frappe.throw(f"Заказ {payload.get('orderNumber') or 'без номера'} не найден на текущей точке")
	# Timestamped v2 updates serialize on the canonical order row. Older updates
	# remain compatible but are excluded from generic manual retry.
	updated_at = payload.get("updatedAt")
	if updated_at:
		frappe.db.sql(
			"select name from `tabPOS Order` where name=%s and business_point=%s for update",
			(name, workplace.business_point),
		)
	doc = frappe.get_doc("POS Order", name)
	if updated_at:
		if doc.last_pos_update_event == event_id:
			return
		incoming = get_datetime(updated_at)
		current = get_datetime(doc.last_pos_update_at) if doc.last_pos_update_at else None
		if current and (
			incoming < current or (incoming == current and event_id <= (doc.last_pos_update_event or ""))
		):
			return
		doc.last_pos_update_at = updated_at
		doc.last_pos_update_event = event_id
	if "phone" in payload:
		doc.phone = payload.get("phone")
	if "contactMethod" in payload:
		doc.contact_method = payload.get("contactMethod") or None
	if "comment" in payload:
		doc.comment = payload.get("comment")
	if "dueAt" in payload:
		doc.due_at = payload.get("dueAt")
	if payload.get("readyAt") and not doc.ready_at:
		doc.ready_at = payload.get("readyAt")
	if payload.get("issuedAt") and not doc.issued_at:
		doc.issued_at = payload.get("issuedAt")
	if not doc.source_receipt and doc.source_sale_id:
		doc.source_receipt = _order_source_receipt(workplace.business_point, doc.source_sale_id)
	if payload.get("status"):
		doc.status = {
			"new": "New",
			"in_progress": "In Progress",
			"ready": "Ready",
			"issued": "Issued",
			"cancelled": "Cancelled",
		}.get(payload["status"], doc.status)
	doc.save(ignore_permissions=True)


def _apply_sale(event_id, workplace, payload):
	sale_id = str(payload.get("id") or event_id)
	if frappe.db.exists("Sales Receipt", {"external_id": sale_id}):
		return

	posting_datetime = (
		_legacy_pos_site_datetime(payload.get("createdAt"))
		if payload.get("createdAt")
		else get_datetime(now())
	)
	shift = _get_or_create_legacy_shift(workplace, payload.get("shiftId"), posting_datetime)
	doc = frappe.new_doc("Sales Receipt")
	doc.external_id = sale_id
	doc.receipt_type = "Sale"
	doc.naming_series = "SALE-.YYYY.-.#####"
	doc.posting_datetime = posting_datetime
	doc.shift = shift.name
	doc.business_entity = shift.business_entity
	doc.business_point = shift.business_point
	doc.warehouse = shift.warehouse
	doc.cashier = shift.cashier
	client = payload.get("customerId")
	if client and frappe.db.exists("Client", client):
		doc.client = client
	doc.source = "POS"
	doc.source_payload_json = frappe.as_json(payload, indent=2)
	doc.comment = _receipt_comment(payload)
	_append_legacy_receipt_lines(doc, payload)
	_append_legacy_payments(doc, payload)
	doc.insert(ignore_permissions=True)
	doc.submit()


def _apply_return(event_id, workplace, payload):
	return_id = str(payload.get("id") or event_id)
	if frappe.db.exists("Sales Receipt", {"external_id": return_id}):
		return

	sale_id = str(payload.get("saleId") or "").strip()
	original_receipt = frappe.db.get_value(
		"Sales Receipt",
		{"external_id": sale_id, "receipt_type": "Sale", "docstatus": 1},
		"name",
	)
	if not original_receipt:
		frappe.throw(f"Исходная продажа {sale_id or 'не указана'} не найдена")

	posting_datetime = (
		_legacy_pos_site_datetime(payload.get("createdAt"))
		if payload.get("createdAt")
		else get_datetime(now())
	)
	shift = _get_or_create_legacy_shift(workplace, payload.get("shiftId"), posting_datetime)
	doc = frappe.new_doc("Sales Receipt")
	doc.external_id = return_id
	doc.receipt_type = "Return"
	doc.naming_series = "RETURN-.YYYY.-.#####"
	doc.original_receipt = original_receipt
	doc.posting_datetime = posting_datetime
	doc.shift = shift.name
	doc.business_entity = shift.business_entity
	doc.business_point = shift.business_point
	doc.warehouse = shift.warehouse
	doc.cashier = shift.cashier
	doc.source = "POS"
	doc.source_payload_json = frappe.as_json(payload, indent=2)
	doc.comment = _receipt_comment(payload)
	_append_legacy_receipt_lines(doc, payload)
	_append_legacy_payments(doc, payload)
	doc.insert(ignore_permissions=True)
	doc.submit()


def _get_or_create_legacy_shift(workplace, external_id, posting_datetime):
	external_id = f"legacy-pos:{workplace.name}:{external_id or posting_datetime.date()}"
	name = frappe.db.get_value("Sales Shift", {"external_id": external_id}, "name")
	if name:
		return frappe.get_doc("Sales Shift", name)

	point = frappe.db.get_value(
		"Business Point",
		workplace.business_point,
		["business_entity", "active"],
		as_dict=True,
	)
	if not point or not point.active:
		frappe.throw("Точка кассы не найдена или отключена")
	warehouse = frappe.db.get_value(
		"Catalog Warehouse",
		{"business_point": workplace.business_point, "active": 1},
		"name",
	)
	if not warehouse:
		frappe.throw("У точки нет активного склада")  # noqa: RUF001

	employee = _get_employee()
	cashier = employee.name if frappe.db.exists("Employee", employee.name) else None
	shift = frappe.new_doc("Sales Shift")
	shift.external_id = external_id
	shift.status = "Open"
	shift.opened_at = posting_datetime
	shift.business_entity = point.business_entity
	shift.business_point = workplace.business_point
	shift.warehouse = warehouse
	shift.cashier = cashier
	shift.source = "POS"
	shift.comment = "Автоматически создана для старого POS API"
	shift.insert(ignore_permissions=True)
	return shift


def _append_legacy_receipt_lines(doc, payload):
	lines = payload.get("lines") or []
	if not lines:
		frappe.throw("В чеке отсутствуют позиции")  # noqa: RUF001

	target_total_minor = round(flt(payload.get("totalMinor")))
	gross_minor = [round(flt(row.get("quantity")) * flt(row.get("unitPriceMinor"))) for row in lines]
	weights = []
	for index, row in enumerate(lines):
		if doc.receipt_type == "Return" and row.get("lineTotalMinor") is not None:
			weights.append(max(0, round(flt(row.get("lineTotalMinor")))))
		else:
			discount = max(0, min(flt(row.get("discountPercent")), 100))
			weights.append(max(0, round(gross_minor[index] * (1 - discount / 100))))
	targets = _allocate_minor_amount(target_total_minor, weights)

	for index, row in enumerate(lines):
		quantity = flt(row.get("quantity"))
		if quantity <= 0:
			frappe.throw("Количество в строке чека должно быть больше нуля")
		item = _resolve_legacy_pos_item(row)
		line_total_minor = targets[index]
		discount_minor = gross_minor[index] - line_total_minor
		if discount_minor < 0:
			frappe.throw("Сумма строки чека превышает её стоимость до скидки")
		doc.append(
			"items",
			{
				"item": item,
				"quantity": quantity,
				"uom": frappe.db.get_value("Catalog Item", item, "stock_uom"),
				"unit_price": flt(row.get("unitPriceMinor")) / 100,
				"discount_amount": discount_minor / 100,
				"storage_location": frappe.db.get_value(
					"Catalog Item Storage",
					{"item": item, "warehouse": doc.warehouse, "active": 1},
					"storage_location",
				),
			},
		)


def _allocate_minor_amount(total, weights):
	if total < 0:
		frappe.throw("Сумма чека не может быть отрицательной")
	weight_total = sum(weights)
	if not weight_total:
		if total:
			frappe.throw("Нельзя распределить сумму чека по нулевым строкам")
		return [0 for _weight in weights]
	result = []
	allocated = 0
	cumulative = 0
	for index, weight in enumerate(weights):
		cumulative += weight
		target = total if index == len(weights) - 1 else round(total * cumulative / weight_total)
		result.append(target - allocated)
		allocated = target
	return result


def _resolve_legacy_pos_item(row):
	item = str(row.get("productId") or "").strip()
	if item and frappe.db.exists("Catalog Item", item):
		return item
	if not item.startswith("free-"):
		frappe.throw(f"Позиция кассы {item or row.get('name') or 'без ID'} не найдена в каталоге")

	generic = "POS-FREE-PRICE"
	if frappe.db.exists("Catalog Item", generic):
		return generic
	if not frappe.db.exists("Catalog Unit", "шт"):
		frappe.throw("Для свободной позиции требуется активная единица измерения «шт»")
	frappe.get_doc(
		{
			"doctype": "Catalog Item",
			"item_code": generic,
			"item_name": "Свободная позиция POS",
			"item_type": "Service",
			"stock_uom": "шт",
			"active": 1,
			"external_code": "legacy-pos-free-price",
		}
	).insert(ignore_permissions=True)
	return generic


def _append_legacy_payments(doc, payload):
	payments = payload.get("payments") or []
	if not payments:
		method = payload.get("paymentMethod")
		payments = [{"method": method, "amountMinor": payload.get("totalMinor")}]
	channels = {"cash": "Cash", "card": "Card", "qr": "QR"}
	for payment in payments:
		channel = channels.get(str(payment.get("method") or "").lower())
		if not channel:
			frappe.throw(f"Неизвестный способ оплаты {payment.get('method')}")
		doc.append(
			"payments",
			{
				"payment_channel": channel,
				"amount": flt(payment.get("amountMinor")) / 100,
				"external_payment_id": payment.get("transactionId"),
			},
		)


def _receipt_comment(payload):
	fiscal_number = str(payload.get("fiscalNumber") or "").strip()
	return f"Фискальный чек: {fiscal_number}" if fiscal_number else None


def _get_workplace_data(employee, point, workplace):
	current_schedule_month = _get_schedule_month(point.name)
	next_schedule_month = _get_schedule_month(point.name, _schedule_month_value(1))
	return {
		"schedule": _get_employee_schedule(employee, point.name),
		"scheduleMonth": current_schedule_month,
		"scheduleCurrentMonth": current_schedule_month,
		"scheduleNextMonth": next_schedule_month,
		"myUpcomingShifts": _get_upcoming_shifts(employee, point.name),
		"operationalCatalog": _get_operational_catalog(point.name),
		"deliveries": _get_delivery_notices(point.name),
		"supplyRequests": _get_supply_requests(point.name),
		"cleaner": _get_cleaner_status(point.name, point),
		"orders": _get_orders(point.name),
	}


def _get_orders(point_name):
	if not _doctype_exists("POS Order"):
		return []
	rows = frappe.get_all(
		"POS Order",
		filters={"business_point": point_name, "creation": [">=", add_days(now_datetime(), -60)]},
		fields=[
			"name",
			"order_number",
			"customer_order_number",
			"phone",
			"contact_method",
			"customer_name",
			"total_amount",
			"paid_amount",
			"status",
			"comment",
			"due_at",
			"creation",
			"created_at",
			"ready_at",
			"issued_at",
			"source_sale_id",
			"source_receipt",
			"fiscal_number",
		],
		order_by="creation desc",
		limit_page_length=5000,
	)
	items = {}
	for item in frappe.get_all(
		"POS Order Item",
		filters={"parent": ["in", [row.name for row in rows] or ["__none__"]]},
		fields=["parent", "item", "item_name", "quantity", "rate"],
		limit_page_length=5000,
	):
		items.setdefault(item.parent, []).append(
			{
				"productId": item.item,
				"name": item.item_name,
				"quantity": flt(item.quantity),
				"unitPriceMinor": round(flt(item.rate) * 100),
			}
		)
	status = {
		"New": "new",
		"In Progress": "in_progress",
		"Ready": "ready",
		"Issued": "issued",
		"Cancelled": "cancelled",
	}
	return [
		{
			"id": x.name,
			"orderNumber": x.order_number,
			"customerOrderNumber": x.customer_order_number,
			"phone": x.phone,
			"contactMethod": x.contact_method,
			"customerName": x.customer_name,
			"lines": items.get(x.name, []),
			"totalMinor": int(flt(x.total_amount) * 100),
			"paidMinor": int(flt(x.paid_amount) * 100),
			"paymentStatus": "paid"
			if flt(x.paid_amount) >= flt(x.total_amount)
			else ("partial" if flt(x.paid_amount) else "unpaid"),
			"status": status.get(x.status, "new"),
			"comment": x.comment,
			"createdAt": _pos_datetime_to_utc(x.created_at or x.creation),
			"dueAt": _pos_datetime_to_utc(x.due_at),
			"readyAt": _pos_datetime_to_utc(x.ready_at),
			"issuedAt": _pos_datetime_to_utc(x.issued_at),
			"sourceSaleId": x.source_sale_id,
			"fiscalNumber": x.fiscal_number,
			"sourceReceipt": x.source_receipt,
		}
		for x in rows
	]


def _doctype_exists(name):
	return bool(frappe.db.exists("DocType", name))


def _schedule_rows(point_name, employee_name=None, month=None, upcoming=False, limit=None):
	if not _doctype_exists("Work Schedule"):
		return []
	conditions = [
		"assignment.business_point=%s",
		"schedule.business_point=%s",
		"schedule.status='Published'",
		"employee.active=1",
	]
	values = [point_name, point_name]
	if employee_name:
		conditions.append("entry.employee=%s")
		values.append(employee_name)
	if month:
		conditions.append("schedule.month=%s")
		conditions.append("entry.work_date between %s and %s")
		values.extend(
			[
				month,
				f"{month[:7]}-01",
				f"{month[:7]}-{calendar.monthrange(int(month[:4]), int(month[5:7]))[1]:02d}",
			]
		)
	elif upcoming:
		conditions.append("entry.work_date>=curdate()")
	where = " and ".join(conditions)
	limit_sql = f" limit {int(limit)}" if limit else ""
	return frappe.db.sql(
		f"""select entry.name, entry.work_date, entry.employee, employee.employee_name,
		entry.shift_template, template.shift_code, template.shift_name,
		entry.start_time entry_start_time, template.start_time template_start_time,
		entry.end_time entry_end_time, template.end_time template_end_time,
		entry.planned_hours entry_planned_hours, template.paid_hours template_paid_hours
		from `tabWork Schedule Entry` entry
		join `tabWork Schedule` schedule on schedule.name=entry.parent
		join `tabEmployee Point Assignment` assignment
			on assignment.parent=entry.employee and assignment.parenttype='Employee'
		join `tabEmployee` employee on employee.name=entry.employee
		left join `tabShift Template` template on template.name=entry.shift_template
		where {where}
		order by entry.work_date, coalesce(entry.start_time, template.start_time), entry.name{limit_sql}""",
		values,
		as_dict=True,
	)


def _schedule_entry(row):
	start = row.entry_start_time or row.template_start_time or ""
	end = row.entry_end_time or row.template_end_time or ""
	planned = row.entry_planned_hours
	if planned is None:
		planned = row.template_paid_hours or 0
	return {
		"id": row.name,
		"date": str(row.work_date),
		"employeeId": row.employee,
		"employeeName": row.employee_name or row.employee,
		"shiftTemplate": row.shift_template,
		"shiftCode": row.shift_code or "",
		"shiftName": row.shift_name or row.shift_template,
		"startTime": str(start),
		"endTime": str(end),
		"plannedHours": flt(planned),
	}


def _schedule_employees(point_name):
	if not _doctype_exists("Employee"):
		return []
	assigned = frappe.get_all(
		"Employee Point Assignment",
		filters={"business_point": point_name, "parenttype": "Employee"},
		pluck="parent",
		limit_page_length=5000,
	)
	if not assigned:
		return []
	return [
		{"id": row.name, "name": row.employee_name or row.name}
		for row in frappe.get_all(
			"Employee",
			filters={"name": ["in", assigned], "active": 1},
			fields=["name", "employee_name"],
			order_by="employee_name asc",
			limit_page_length=5000,
		)
	]


def _schedule_month_value(month_offset=0):
	today = getdate(nowdate())
	month_index = today.year * 12 + today.month - 1 + int(month_offset)
	year, zero_based_month = divmod(month_index, 12)
	return f"{year:04d}-{zero_based_month + 1:02d}-01"


def _get_schedule_month(point_name, month=None):
	month = month or _schedule_month_value()
	year, month_number = int(month[:4]), int(month[5:7])
	rows = _schedule_rows(point_name, month=month)
	return {
		"month": month[:7],
		"days": calendar.monthrange(year, month_number)[1],
		"employees": _schedule_employees(point_name),
		"entries": [_schedule_entry(row) for row in rows],
	}


def _get_upcoming_shifts(employee, point_name):
	if employee.name == "Administrator":
		return []
	rows = _schedule_rows(point_name, employee_name=employee.name, upcoming=True, limit=5)
	return [
		{
			key: value
			for key, value in _schedule_entry(row).items()
			if key not in {"employeeId", "employeeName"}
		}
		for row in rows
	]


def _get_employee_schedule(employee, point_name):
	# Legacy personal schedule retained for cached clients; new UI uses explicit fields above.
	if employee.name == "Administrator" or not _doctype_exists("Work Schedule"):
		return []
	rows = _schedule_rows(point_name, employee_name=employee.name, upcoming=True, limit=31)
	return [
		{
			"id": row.name,
			"date": str(row.work_date),
			"shiftName": row.shift_name or row.shift_template,
			"startTime": str(row.entry_start_time or row.template_start_time or ""),
			"endTime": str(row.entry_end_time or row.template_end_time or ""),
			"plannedHours": flt(
				row.entry_planned_hours
				if row.entry_planned_hours is not None
				else row.template_paid_hours or 0
			),
		}
		for row in rows
	]


def _get_delivery_notices(point_name):
	rows = frappe.get_all(
		"Purchase Order",
		filters={"business_point": point_name, "docstatus": 1, "order_status": ["!=", "Принято"]},
		fields=[
			"name",
			"supplier",
			"expected_date",
			"order_status",
			"delivery_company",
			"delivery_code",
			"delivery_note",
			"remarks",
		],
		order_by="expected_date asc, creation asc",
		limit_page_length=50,
	)
	if not rows:
		return []

	order_names = [row.name for row in rows]
	order_items = frappe.get_all(
		"Purchase Order Item",
		filters={"parent": ["in", order_names], "parenttype": "Purchase Order"},
		fields=[
			"name",
			"parent",
			"item",
			"item_code",
			"uom",
			"quantity",
			"received_quantity",
		],
		order_by="idx asc",
		limit_page_length=5000,
	)
	item_names = {
		row.name: row.item_name
		for row in frappe.get_all(
			"Catalog Item",
			filters={"name": ["in", list({row.item for row in order_items}) or ["__none__"]]},
			fields=["name", "item_name"],
			limit_page_length=5000,
		)
	}
	by_order = {}
	for item in order_items:
		remaining = max(0, flt(item.quantity) - flt(item.received_quantity))
		if remaining <= 0:
			continue
		by_order.setdefault(item.parent, []).append(
			{
				"purchaseOrderItemId": item.name,
				"itemId": item.item,
				"itemName": item_names.get(item.item) or item.item_code or item.item,
				"itemCode": item.item_code or "",
				"uom": item.uom or "шт",
				"orderedQuantity": flt(item.quantity),
				"receivedQuantity": flt(item.received_quantity),
				"remainingQuantity": remaining,
			}
		)

	result = []
	for row in rows:
		items = by_order.get(row.name, [])
		if not items:
			continue
		result.append(
			{
				"id": row.name,
				"supplier": row.supplier,
				"expectedDate": str(row.expected_date or ""),
				"deliveryCompany": row.delivery_company or "",
				"deliveryCode": row.delivery_code or "",
				"receivingNote": row.delivery_note or "",
				"comment": row.remarks or "",
				"details": row.delivery_note or row.remarks or "",
				"status": row.order_status,
				"items": items,
			}
		)
	return result


def _get_supply_requests(point_name):
	if not _doctype_exists("Point Supply Request"):
		return []
	return [
		{
			"id": row.name,
			"createdAt": _pos_datetime_to_utc(row.creation),
			"itemName": row.item_name,
			"quantity": flt(row.quantity),
			"status": row.status,
			"comment": row.comment or "",
		}
		for row in frappe.get_all(
			"Point Supply Request",
			filters={"business_point": point_name, "status": ["not in", ["Закрыта", "Отклонена"]]},
			fields=["name", "creation", "item_name", "quantity", "status", "comment"],
			order_by="creation desc",
			limit_page_length=50,
		)
	]


def _cleaning_config(point):
	amount = flt(point.get("cleaning_payout_amount")) if point else 0
	visits = point.get("cleaning_every_n_visits") if point else None
	amount = amount if amount > 0 else 2000
	visits_number = flt(visits)
	visits = int(visits_number) if visits_number >= 1 and visits_number == int(visits_number) else 4
	return {"payoutAmountMinor": round(amount * 100), "everyNVisits": visits}


def _get_cleaner_status(point_name, point=None):
	config = _cleaning_config(point or frappe.get_doc("Business Point", point_name))
	if not _doctype_exists("Cleaner Visit"):
		return {"visitsSincePayment": 0, "paymentDueMinor": 0, "recentVisits": [], **config}
	rows = frappe.get_all(
		"Cleaner Visit",
		filters={"business_point": point_name},
		fields=["name", "visit_date", "recorded_by_name", "paid"],
		order_by="visit_date desc, creation desc",
		limit_page_length=12,
	)
	unpaid = frappe.db.count("Cleaner Visit", {"business_point": point_name, "paid": 0})
	return {
		"visitsSincePayment": unpaid,
		"paymentDueMinor": config["payoutAmountMinor"] if unpaid >= config["everyNVisits"] else 0,
		"recentVisits": [
			{
				"id": row.name,
				"visitDate": str(row.visit_date),
				"recordedBy": row.recorded_by_name,
				"paid": bool(row.paid),
			}
			for row in rows
		],
		**config,
	}


def _point_context(workplace):
	point = frappe.get_doc("Business Point", workplace.business_point)
	warehouse = frappe.db.get_value("Catalog Warehouse", {"business_point": point.name, "active": 1}, "name")
	return point, warehouse


def _apply_stock_write_off(event_id, workplace, payload):
	point, warehouse = _point_context(workplace)
	item = payload.get("productId")
	if not warehouse or not frappe.db.exists("Catalog Item", item):
		frappe.throw("Для списания не найден товар или склад точки")
	doc = frappe.get_doc(
		{
			"doctype": "Stock Write Off",
			"posting_datetime": now(),
			"business_entity": point.business_entity,
			"business_point": point.name,
			"warehouse": warehouse,
			"reason": payload.get("reason") or "Другое",
			"remarks": (payload.get("comment") or "") + f"\nPOS event: {event_id}",
			"items": [
				{
					"item": item,
					"quantity": flt(payload.get("quantity")),
					"storage_location": frappe.db.get_value(
						"Catalog Item Storage",
						{"item": item, "warehouse": warehouse, "active": 1},
						"storage_location",
					),
				}
			],
		}
	).insert(ignore_permissions=True)
	doc.submit()


def _apply_supply_request(event_id, workplace, payload):
	if frappe.db.exists("Point Supply Request", {"source_pos_event": event_id}):
		return
	point, warehouse = _point_context(workplace)
	frappe.get_doc(
		{
			"doctype": "Point Supply Request",
			"request_date": nowdate(),
			"business_entity": point.business_entity,
			"business_point": point.name,
			"warehouse": warehouse,
			"item": payload.get("productId")
			if payload.get("productId") and frappe.db.exists("Catalog Item", payload.get("productId"))
			else None,
			"item_name": payload.get("itemName"),
			"quantity": flt(payload.get("quantity")),
			"comment": payload.get("comment") or "",
			"requested_by": frappe.session.user,
			"source_pos_event": event_id,
		}
	).insert(ignore_permissions=True)


def _apply_cleaner_visit(event_id, workplace, payload):
	if frappe.db.exists("Cleaner Visit", {"source_pos_event": event_id}):
		return
	frappe.get_doc(
		{
			"doctype": "Cleaner Visit",
			"business_point": workplace.business_point,
			"visit_date": getdate(payload.get("visitDate") or nowdate()),
			"recorded_by": frappe.session.user,
			"recorded_by_name": payload.get("recordedBy") or frappe.session.user,
			"source_pos_event": event_id,
		}
	).insert(ignore_permissions=True)


def _apply_cleaner_payment(event_id, workplace, payload):
	visits = frappe.get_all(
		"Cleaner Visit",
		filters={"business_point": workplace.business_point, "paid": 0},
		pluck="name",
		order_by="visit_date asc, creation asc",
		limit_page_length=4,
	)
	if len(visits) < 4:
		frappe.throw("Для выплаты должно быть зарегистрировано четыре неоплаченных посещения")
	for visit in visits:
		frappe.db.set_value(
			"Cleaner Visit", visit, {"paid": 1, "paid_at": now(), "payment_pos_event": event_id}
		)


def _apply_cash_count(event_id, workplace, payload):
	if frappe.db.exists("POS Cash Count", {"source_pos_event": event_id}):
		return
	frappe.get_doc(
		{
			"doctype": "POS Cash Count",
			"business_point": workplace.business_point,
			"pos_workplace": workplace.name,
			"counted_at": _legacy_pos_site_datetime(payload.get("createdAt"))
			if payload.get("createdAt")
			else now(),
			"count_type": payload.get("countType"),
			"cashier_user": frappe.session.user,
			"expected_amount": flt(payload.get("expectedMinor")) / 100,
			"counted_amount": flt(payload.get("totalMinor")) / 100,
			"difference": flt(payload.get("differenceMinor")) / 100,
			"source_pos_event": event_id,
			"lines": [
				{"denomination": flt(row.get("denominationMinor")) / 100, "quantity": row.get("quantity")}
				for row in payload.get("lines") or []
			],
		}
	).insert(ignore_permissions=True)
