from __future__ import annotations

import frappe
from frappe.utils import flt, get_datetime, getdate, now, nowdate

from raspechatka.pricing import resolve_item_price


@frappe.whitelist()
def get_bootstrap(workplace_code=None):
	"""Return the cashier, point rules and point-specific catalog for POS."""
	if frappe.session.user == "Guest":
		frappe.throw("Требуется авторизация", frappe.AuthenticationError)

	employee = _get_employee()
	allowed_points = _employee_points(employee)
	workplace = _get_workplace(workplace_code, allowed_points)
	point = frappe.get_doc("Business Point", workplace.business_point)

	return {
		"employee": {"id": employee.get("name"), "name": employee.get("employee_name") or frappe.session.user},
		"point": {"id": point.name, "name": point.point_name},
		"workplace": {"id": workplace.name, "name": workplace.workplace_name},
		"rules": {
			"allowFreePrice": bool(point.allow_free_price),
			"allowRemoveCartItem": bool(point.allow_remove_cart_item),
			"allowDiscounts": bool(point.allow_discounts),
			"maxDiscountPercent": flt(point.max_discount_percent),
			"acceptsCash": bool(point.accepts_cash),
			"acceptsCard": bool(point.accepts_card),
			"acceptsQr": bool(point.accepts_qr),
		},
		"products": _get_products(point.name),
		"customers": _get_customers(),
		"workplaceData": _get_workplace_data(employee, point, workplace),
	}


@frappe.whitelist(methods=["POST"])
def push_events(workplace_code=None, events=None):
	"""Accept the local POS outbox idempotently.

	The event_id is generated by the workstation and is unique. Re-sending the
	same batch after a network interruption therefore never duplicates a sale.
	"""
	if frappe.session.user == "Guest":
		frappe.throw("Требуется авторизация", frappe.AuthenticationError)

	events = frappe.parse_json(events) if isinstance(events, str) else (events or [])
	if not isinstance(events, list):
		frappe.throw("Ожидается список событий")
	if len(events) > 100:
		frappe.throw("За один запрос можно передать не более 100 событий")

	employee = _get_employee()
	workplace = _get_workplace(workplace_code, _employee_points(employee))
	accepted = []
	for event in events:
		event_id = str(event.get("id") or "").strip()
		event_type = str(event.get("eventType") or "").strip()
		if not event_id or not event_type:
			frappe.throw("В событии отсутствует id или eventType")
		if not frappe.db.exists("POS Event", event_id):
			frappe.get_doc({
				"doctype": "POS Event",
				"event_id": event_id,
				"event_type": event_type,
				"business_point": workplace.business_point,
				"pos_workplace": workplace.name,
				"cashier_user": frappe.session.user,
				"occurred_at": get_datetime(event.get("createdAt")) if event.get("createdAt") else now(),
				"payload_json": frappe.as_json(event.get("payload"), indent=2),
				"received_at": now(),
			}).insert(ignore_permissions=True)
			_apply_pos_event(event_type, event_id, workplace, event.get("payload") or {})
		accepted.append(event_id)

	return {"accepted": accepted}


def _get_employee():
	rows = frappe.get_all(
		"Employee",
		filters={"user": frappe.session.user, "active": 1},
		fields=["name", "employee_name"],
		limit_page_length=1,
	)
	if rows:
		return rows[0]
	if frappe.session.user == "Administrator":
		return frappe._dict(name="Administrator", employee_name="Администратор")
	frappe.throw("Для пользователя не создан активный сотрудник", frappe.PermissionError)


def _employee_points(employee):
	if employee.name == "Administrator":
		return frappe.get_all("Business Point", filters={"active": 1}, pluck="name")
	return frappe.get_all(
		"Employee Point Assignment",
		filters={"parent": employee.name, "parenttype": "Employee"},
		pluck="business_point",
	)


def _get_workplace(workplace_code, allowed_points):
	filters = {"active": 1, "business_point": ["in", allowed_points or ["__none__"]]}
	if workplace_code:
		filters["workplace_code"] = workplace_code
	rows = frappe.get_all(
		"POS Workplace",
		filters=filters,
		fields=["name", "workplace_name", "workplace_code", "business_point"],
		order_by="workplace_name asc",
		limit_page_length=2,
	)
	if not rows:
		frappe.throw("Для доступной точки не настроено рабочее место кассы")
	if not workplace_code and len(rows) > 1:
		frappe.throw("Укажите код рабочего места: пользователю доступно несколько касс")
	return rows[0]


def _get_products(point_name):
	today = getdate(nowdate())
	assortments = frappe.get_all(
		"Catalog Assortment",
		filters={"business_point": point_name, "enabled": 1, "visible_in_pos": 1},
		fields=["item", "valid_from", "valid_upto"],
		limit_page_length=5000,
	)
	assortments = [
		row for row in assortments
		if (not row.valid_from or getdate(row.valid_from) <= today)
		and (not row.valid_upto or getdate(row.valid_upto) >= today)
	]
	if not assortments:
		return []

	warehouse = frappe.db.get_value("Catalog Warehouse", {"business_point": point_name, "active": 1}, "name")
	balances = dict(frappe.db.sql(
		"""select item, coalesce(sum(actual_qty), 0)
		from `tabStock Ledger Entry` where warehouse=%s group by item""",
		(warehouse,),
		as_list=True,
	)) if warehouse else {}
	storage = {
		row.item: row.full_address
		for row in frappe.get_all(
			"Catalog Item Storage",
			filters={"warehouse": warehouse, "active": 1} if warehouse else {"name": "__none__"},
			fields=["item", "full_address"],
			limit_page_length=5000,
		)
	}
	items = {
		row.name: row
		for row in frappe.get_all(
			"Catalog Item",
			filters={"name": ["in", [row.item for row in assortments]], "active": 1},
			fields=[
				"name",
				"item_name",
				"item_code",
				"item_type",
				"catalog_group",
				"stock_uom",
				"track_inventory",
				"prevent_discounts",
				"has_variants",
			],
			limit_page_length=5000,
		)
	}
	group_names = {
		row.name: row.group_name
		for row in frappe.get_all(
			"Catalog Group",
			filters={"name": ["in", list({row.catalog_group for row in items.values() if row.catalog_group}) or ["__none__"]]},
			fields=["name", "group_name"],
			limit_page_length=1000,
		)
	}
	result = []
	for assortment in assortments:
		item = items.get(assortment.item)
		if not item or item.has_variants:
			continue
		resolved_price = resolve_item_price(
			item.name,
			point_name,
			quantity=1,
			uom=item.stock_uom,
			required=False,
		)
		if not resolved_price and not frappe.db.get_value("Business Point", point_name, "allow_free_price"):
			continue
		price = resolved_price["rate"] if resolved_price else 0
		barcode = frappe.db.get_value(
			"Catalog Item Barcode",
			{"parent": item.name, "parenttype": "Catalog Item", "parentfield": "barcodes"},
			"barcode",
		)
		result.append({
			"id": item.name,
			"name": item.item_name,
			"sku": item.item_code,
			"category": group_names.get(item.catalog_group) or "Без группы",
			"type": {
				"Product": "product",
				"Variant": "product",
				"Service": "service",
				"Bundle": "bundle",
			}.get(item.item_type, "service"),
			"uom": item.stock_uom or "шт",
			"priceMinor": round(price * 100),
			"barcode": barcode,
			"stock": flt(balances.get(item.name)) if item.track_inventory else None,
			"trackInventory": bool(item.track_inventory),
			"allowNegativeStock": False,
			"minimumSalePriceMinor": 0,
			"preventDiscounts": bool(item.prevent_discounts),
			"storageAddress": storage.get(item.name) or "",
		})
	return sorted(result, key=lambda row: (row["category"], row["name"]))


def _get_customers():
	purchases = {
		row.client: row
		for row in frappe.get_all(
			"Client Purchase",
			fields=["client", "count(name) as purchase_count", "sum(net_amount - returned_amount) as total_spent"],
			group_by="client",
			limit_page_length=10000,
		)
	}
	return [
		{
			"id": row.name,
			"name": row.client_name,
			"phone": row.phone,
			"discountPercent": flt(row.discount_percent),
			"purchaseCount": int((purchases.get(row.name) or {}).get("purchase_count") or 0),
			"totalSpentMinor": round(flt((purchases.get(row.name) or {}).get("total_spent")) * 100),
		}
		for row in frappe.get_all(
			"Client",
			filters={"active": 1},
			fields=["name", "client_name", "phone", "discount_percent"],
			order_by="client_name asc",
			limit_page_length=10000,
		)
	]


def _apply_pos_event(event_type, event_id, workplace, payload):
	if event_type == "sale.completed":
		_apply_sale(event_id, workplace, payload)
	elif event_type == "sale.returned":
		_apply_return(event_id, workplace, payload)
	elif event_type == "stock.write_off.requested":
		_apply_stock_write_off(event_id, workplace, payload)
	elif event_type == "point.supply.requested":
		_apply_supply_request(event_id, workplace, payload)
	elif event_type == "cleaner.visit.recorded":
		_apply_cleaner_visit(event_id, workplace, payload)
	elif event_type == "cleaner.paid":
		_apply_cleaner_payment(event_id, workplace, payload)
	elif event_type == "cash.counted":
		_apply_cash_count(event_id, workplace, payload)
	elif event_type == "order.created":
		_apply_order_created(event_id, workplace, payload)
	elif event_type == "order.updated":
		_apply_order_updated(event_id, workplace, payload)


def _apply_order_created(event_id, workplace, payload):
	if not _doctype_exists("POS Order") or frappe.db.exists("POS Order", {"source_pos_event": event_id}):
		return
	status = {"new": "New", "in_progress": "In Progress", "ready": "Ready", "issued": "Issued", "cancelled": "Cancelled"}.get(payload.get("status"), "New")
	doc = frappe.get_doc({"doctype": "POS Order", "order_number": payload.get("orderNumber"), "phone": payload.get("phone"),
		"customer_name": payload.get("customerName"), "business_point": workplace.business_point,
		"source_pos_event": event_id, "source_sale_id": payload.get("sourceSaleId"), "fiscal_number": payload.get("fiscalNumber"),
		"total_amount": flt(payload.get("totalMinor")) / 100, "paid_amount": flt(payload.get("paidMinor")) / 100,
		"status": status, "comment": payload.get("comment"), "due_at": payload.get("dueAt"),
		"items": [{"item": x.get("productId") if frappe.db.exists("Catalog Item", x.get("productId")) else None,
			"item_name": x.get("name"), "quantity": flt(x.get("quantity")), "rate": flt(x.get("unitPriceMinor")) / 100,
			"amount": flt(x.get("quantity")) * flt(x.get("unitPriceMinor")) / 100} for x in payload.get("lines", [])]})
	doc.insert(ignore_permissions=True)


def _apply_order_updated(event_id, workplace, payload):
	if not _doctype_exists("POS Order"):
		return
	name = frappe.db.get_value("POS Order", {"order_number": payload.get("orderNumber")}, "name")
	if not name:
		return
	doc = frappe.get_doc("POS Order", name)
	for field in ("phone", "comment", "due_at"):
		if field in payload:
			setattr(doc, field, payload.get(field))
	if payload.get("status"):
		doc.status = {"new": "New", "in_progress": "In Progress", "ready": "Ready", "issued": "Issued", "cancelled": "Cancelled"}.get(payload["status"], doc.status)
	doc.save(ignore_permissions=True)


def _apply_sale(event_id, workplace, payload):
	sale_id = payload.get("id") or event_id
	client = payload.get("customerId")
	lines = payload.get("lines") or []
	total = flt(payload.get("totalMinor")) / 100
	gross = sum(flt(line.get("quantity")) * flt(line.get("unitPriceMinor")) / 100 for line in lines)
	if client and frappe.db.exists("Client", client) and not frappe.db.exists("Client Purchase", {"source_document": sale_id}):
		frappe.get_doc({
			"doctype": "Client Purchase",
			"purchase_datetime": get_datetime(payload.get("createdAt")) if payload.get("createdAt") else now(),
			"client": client,
			"business_point": workplace.business_point,
			"source_doctype": "POS Event",
			"source_document": sale_id,
			"receipt_number": payload.get("fiscalNumber"),
			"gross_amount": gross,
			"discount_amount": max(0, gross - total),
			"net_amount": total,
			"loyalty_discount_percent": flt(payload.get("receiptDiscountPercent")),
			"returned_amount": 0,
			"status": "Completed",
			"items": [{
				"item": line.get("productId") if frappe.db.exists("Catalog Item", line.get("productId")) else None,
				"item_name": line.get("name"),
				"quantity": flt(line.get("quantity")),
				"rate": flt(line.get("unitPriceMinor")) / 100,
				"amount": flt(line.get("quantity")) * flt(line.get("unitPriceMinor")) / 100,
			} for line in lines],
		}).insert(ignore_permissions=True)
	_create_stock_entries(workplace, sale_id, "POS Sale", lines, multiplier=-1)


def _apply_return(event_id, workplace, payload):
	return_id = payload.get("id") or event_id
	sale_id = payload.get("saleId")
	total = flt(payload.get("totalMinor")) / 100
	purchase_name = frappe.db.get_value("Client Purchase", {"source_document": sale_id}, "name")
	if purchase_name:
		purchase = frappe.get_doc("Client Purchase", purchase_name)
		purchase.returned_amount = min(flt(purchase.net_amount), flt(purchase.returned_amount) + total)
		purchase.status = "Returned" if purchase.returned_amount >= flt(purchase.net_amount) else "Partially Returned"
		purchase.cancelled = 1 if purchase.status == "Returned" else 0
		purchase.save(ignore_permissions=True)
	_create_stock_entries(workplace, return_id, "POS Return", payload.get("lines") or [], multiplier=1)


def _create_stock_entries(workplace, voucher_no, voucher_type, lines, multiplier):
	warehouse = frappe.db.get_value("Catalog Warehouse", {"business_point": workplace.business_point, "active": 1}, "name")
	if not warehouse:
		return
	for index, line in enumerate(lines, start=1):
		item_name = line.get("productId")
		item = frappe.db.get_value(
			"Catalog Item", item_name,
			["item_type", "track_inventory", "allow_negative_stock"], as_dict=True,
		) if item_name else None
		if not item or item.item_type not in {"Product", "Variant"} or not item.track_inventory:
			continue
		quantity = multiplier * flt(line.get("quantity"))
		if quantity < 0 and not item.allow_negative_stock:
			balance = flt(frappe.db.sql(
				"""select coalesce(sum(actual_qty), 0) from `tabStock Ledger Entry`
				where item=%s and warehouse=%s""",
				(item_name, warehouse),
			)[0][0])
			if balance + quantity < 0:
				frappe.throw(
					f"Недостаточно остатка «{frappe.db.get_value('Catalog Item', item_name, 'item_name') or item_name}»: доступно {balance:g}"
				)
		rate = _stock_rate(item_name, warehouse)
		frappe.get_doc({
			"doctype": "Stock Ledger Entry",
			"posting_datetime": now(),
			"item": item_name,
			"warehouse": warehouse,
			"actual_qty": quantity,
			"incoming_rate": rate,
			"stock_value_difference": quantity * rate,
			"voucher_type": voucher_type,
			"voucher_no": voucher_no,
			"voucher_detail_no": f"{voucher_no}:{index}",
			"is_reversal": 1 if multiplier > 0 else 0,
		}).insert(ignore_permissions=True)


def _stock_rate(item_name, warehouse):
	return flt(frappe.db.get_value(
		"Stock Ledger Entry",
		{"item": item_name, "warehouse": warehouse, "incoming_rate": [">", 0]},
		"incoming_rate",
		order_by="posting_datetime desc, creation desc",
	) or 0)


def _get_workplace_data(employee, point, workplace):
	return {
		"schedule": _get_employee_schedule(employee, point.name),
		"deliveries": _get_delivery_notices(point.name),
		"supplyRequests": _get_supply_requests(point.name),
		"cleaner": _get_cleaner_status(point.name),
		"orders": _get_orders(point.name),
	}


def _get_orders(point_name):
	if not _doctype_exists("POS Order"):
		return []
	rows = frappe.get_all("POS Order", filters={"business_point": point_name}, fields=["name", "order_number", "phone", "customer_name", "total_amount", "paid_amount", "status", "comment", "due_at", "creation", "source_sale_id", "fiscal_number"], order_by="creation desc", limit_page_length=200)
	status = {"New": "new", "In Progress": "in_progress", "Ready": "ready", "Issued": "issued", "Cancelled": "cancelled"}
	return [{"id": x.name, "orderNumber": x.order_number, "phone": x.phone, "customerName": x.customer_name, "lines": [], "totalMinor": int(flt(x.total_amount) * 100), "paidMinor": int(flt(x.paid_amount) * 100), "paymentStatus": "paid" if flt(x.paid_amount) >= flt(x.total_amount) else ("partial" if flt(x.paid_amount) else "unpaid"), "status": status.get(x.status, "new"), "comment": x.comment, "createdAt": str(x.creation), "dueAt": x.due_at, "sourceSaleId": x.source_sale_id, "fiscalNumber": x.fiscal_number} for x in rows]


def _doctype_exists(name):
	return bool(frappe.db.exists("DocType", name))


def _get_employee_schedule(employee, point_name):
	if employee.name == "Administrator" or not _doctype_exists("Work Schedule"):
		return []
	rows = frappe.db.sql(
		"""select entry.name, entry.work_date, entry.shift_template, entry.start_time,
		entry.end_time, entry.planned_hours
		from `tabWork Schedule Entry` entry
		join `tabWork Schedule` schedule on schedule.name=entry.parent
		where entry.employee=%s and schedule.business_point=%s and schedule.status='Published'
		and entry.work_date between curdate() and date_add(curdate(), interval 31 day)
		order by entry.work_date, entry.start_time""",
		(employee.name, point_name), as_dict=True,
	)
	return [{
		"id": row.name, "date": str(row.work_date), "shiftName": row.shift_template,
		"startTime": str(row.start_time or ""), "endTime": str(row.end_time or ""),
		"plannedHours": flt(row.planned_hours),
	} for row in rows]


def _get_delivery_notices(point_name):
	rows = frappe.get_all(
		"Purchase Order",
		filters={"business_point": point_name, "docstatus": 1, "order_status": ["!=", "Принято"]},
		fields=["name", "supplier", "expected_date", "order_status", "delivery_company", "delivery_code", "delivery_note", "remarks"],
		order_by="expected_date asc, creation asc", limit_page_length=50,
	)
	return [{
		"id": row.name, "supplier": row.supplier, "expectedDate": str(row.expected_date or ""),
		"deliveryCompany": row.delivery_company or "", "deliveryCode": row.delivery_code or "",
		"details": row.delivery_note or row.remarks or "", "status": row.order_status,
	} for row in rows]


def _get_supply_requests(point_name):
	if not _doctype_exists("Point Supply Request"):
		return []
	return [{
		"id": row.name, "createdAt": str(row.creation), "itemName": row.item_name,
		"quantity": flt(row.quantity), "status": row.status, "comment": row.comment or "",
	} for row in frappe.get_all(
		"Point Supply Request", filters={"business_point": point_name, "status": ["not in", ["Закрыта", "Отклонена"]]},
		fields=["name", "creation", "item_name", "quantity", "status", "comment"],
		order_by="creation desc", limit_page_length=50,
	)]


def _get_cleaner_status(point_name):
	if not _doctype_exists("Cleaner Visit"):
		return {"visitsSincePayment": 0, "paymentDueMinor": 0, "recentVisits": []}
	rows = frappe.get_all(
		"Cleaner Visit", filters={"business_point": point_name},
		fields=["name", "visit_date", "recorded_by_name", "paid"],
		order_by="visit_date desc, creation desc", limit_page_length=12,
	)
	unpaid = frappe.db.count("Cleaner Visit", {"business_point": point_name, "paid": 0})
	return {
		"visitsSincePayment": unpaid, "paymentDueMinor": 200000 if unpaid >= 4 else 0,
		"recentVisits": [{"id": row.name, "visitDate": str(row.visit_date), "recordedBy": row.recorded_by_name, "paid": bool(row.paid)} for row in rows],
	}


def _point_context(workplace):
	point = frappe.get_doc("Business Point", workplace.business_point)
	warehouse = frappe.db.get_value("Catalog Warehouse", {"business_point": point.name, "active": 1}, "name")
	return point, warehouse


def _apply_stock_write_off(event_id, workplace, payload):
	point, warehouse = _point_context(workplace)
	item = payload.get("productId")
	if not warehouse or not frappe.db.exists("Catalog Item", item):
		frappe.throw("Для списания не найден товар или склад точки")
	doc = frappe.get_doc({
		"doctype": "Stock Write Off", "posting_datetime": now(),
		"business_entity": point.business_entity, "business_point": point.name,
		"warehouse": warehouse, "reason": payload.get("reason") or "Другое",
		"remarks": (payload.get("comment") or "") + f"\nPOS event: {event_id}",
		"items": [{"item": item, "quantity": flt(payload.get("quantity")),
			"storage_location": frappe.db.get_value("Catalog Item Storage", {"item": item, "warehouse": warehouse, "active": 1}, "storage_location")}],
	}).insert(ignore_permissions=True)
	doc.submit()


def _apply_supply_request(event_id, workplace, payload):
	if frappe.db.exists("Point Supply Request", {"source_pos_event": event_id}):
		return
	point, warehouse = _point_context(workplace)
	frappe.get_doc({
		"doctype": "Point Supply Request", "request_date": nowdate(),
		"business_entity": point.business_entity, "business_point": point.name, "warehouse": warehouse,
		"item": payload.get("productId") if payload.get("productId") and frappe.db.exists("Catalog Item", payload.get("productId")) else None,
		"item_name": payload.get("itemName"), "quantity": flt(payload.get("quantity")),
		"comment": payload.get("comment") or "", "requested_by": frappe.session.user,
		"source_pos_event": event_id,
	}).insert(ignore_permissions=True)


def _apply_cleaner_visit(event_id, workplace, payload):
	if frappe.db.exists("Cleaner Visit", {"source_pos_event": event_id}):
		return
	frappe.get_doc({
		"doctype": "Cleaner Visit", "business_point": workplace.business_point,
		"visit_date": getdate(payload.get("visitDate") or nowdate()), "recorded_by": frappe.session.user,
		"recorded_by_name": payload.get("recordedBy") or frappe.session.user, "source_pos_event": event_id,
	}).insert(ignore_permissions=True)


def _apply_cleaner_payment(event_id, workplace, payload):
	visits = frappe.get_all(
		"Cleaner Visit", filters={"business_point": workplace.business_point, "paid": 0},
		pluck="name", order_by="visit_date asc, creation asc", limit_page_length=4,
	)
	if len(visits) < 4:
		frappe.throw("Для выплаты должно быть зарегистрировано четыре неоплаченных посещения")
	for visit in visits:
		frappe.db.set_value("Cleaner Visit", visit, {"paid": 1, "paid_at": now(), "payment_pos_event": event_id})


def _apply_cash_count(event_id, workplace, payload):
	if frappe.db.exists("POS Cash Count", {"source_pos_event": event_id}):
		return
	frappe.get_doc({
		"doctype": "POS Cash Count", "business_point": workplace.business_point,
		"pos_workplace": workplace.name, "counted_at": get_datetime(payload.get("createdAt")) if payload.get("createdAt") else now(),
		"count_type": payload.get("countType"), "cashier_user": frappe.session.user,
		"expected_amount": flt(payload.get("expectedMinor")) / 100,
		"counted_amount": flt(payload.get("totalMinor")) / 100,
		"difference": flt(payload.get("differenceMinor")) / 100, "source_pos_event": event_id,
		"lines": [{"denomination": flt(row.get("denominationMinor")) / 100, "quantity": row.get("quantity")} for row in payload.get("lines") or []],
	}).insert(ignore_permissions=True)

