import { useMemo, useState } from 'react'
import type { Order, SaleSummary } from '../../shared/contracts'

const money=(minor:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(minor/100)
const short=(phone:string)=>{const digits=phone.replace(/\D/g,'');return digits.slice(-4)||'—'}
const statusName=(s:Order['status'])=>s==='ready'?'Готов':s==='issued'?'Выдан':s==='cancelled'?'Отменён':'В работе'
const overdue=(o:Order)=>Boolean(o.dueAt&&new Date(o.dueAt).getTime()<Date.now()&&o.status!=='ready'&&o.status!=='issued')
type Props={orders:Order[];onChanged:()=>Promise<void>;notify:(text:string)=>void}

export default function OrdersPage({orders,onChanged,notify}:Props){
 const [editing,setEditing]=useState<Order|null>(null);const [creating,setCreating]=useState(false)
 const active=useMemo(()=>orders.filter(o=>['new','in_progress','ready'].includes(o.status)).sort((a,b)=>{const ar=a.status==='ready'?1:0,br=b.status==='ready'?1:0;if(ar!==br)return ar-br;const ao=overdue(a)?0:1,bo=overdue(b)?0:1;if(ao!==bo)return ao-bo;return (new Date(a.dueAt||'9999').getTime()-new Date(b.dueAt||'9999').getTime())}),[orders])
 const update=async(order:Order,status:Order['status'])=>{try{await window.raspechatkaPos.updateOrder({id:order.id,status});await onChanged();notify(status==='ready'?'Заказ отмечен как готовый':'Заказ выдан')}catch(e){notify(e instanceof Error?e.message:String(e))}}
 return <main className="page orders-page"><div className="page-heading orders-heading"><h1>Заказы</h1><button className="primary" onClick={()=>setCreating(true)}>+ Создать заказ</button></div><p className="orders-note">Рабочая очередь оплаченных заказов текущей точки.</p><div className="data-table orders-table"><header><span>Заказ</span><span>Телефон</span><span>Описание заказа</span><span>Оплата</span><span>Создан</span><span>Срок готовности</span><span>Статус</span><span>Действие</span></header>{active.length?active.map(o=><div key={o.id} className={overdue(o)?'order-overdue':''}><b>№ {short(o.phone)}<small>{o.orderNumber}</small></b><span>{o.phone}</span><span>{o.comment||'—'}</span><span>Оплачено · {money(o.totalMinor)}{o.fiscalNumber?' · чек '+o.fiscalNumber:''}</span><span>{new Date(o.createdAt).toLocaleString('ru-RU')}</span><span>{o.dueAt?new Date(o.dueAt).toLocaleString('ru-RU'):'—'}{overdue(o)&&<small>Просрочен</small>}</span><span className={'order-status '+o.status}>{statusName(o.status)}</span><div className="order-actions"><button onClick={()=>setEditing(o)} title="Изменить телефон, описание или срок">Изменить</button>{o.status==='ready'?<button className="primary" onClick={()=>void update(o,'issued')}>Выдан</button>:<button className="primary" onClick={()=>void update(o,'ready')}>Готово</button>}</div></div>):<div className="page-empty">Активных заказов нет</div>}</div>{editing&&<EditOrder order={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await onChanged();notify('Заказ сохранён')}}/>}{creating&&<CreateOrder close={()=>setCreating(false)} saved={async()=>{setCreating(false);await onChanged();notify('Заказ создан')}}/>}</main>
}

function EditOrder({order,close,saved}:{order:Order;close:()=>void;saved:()=>Promise<void>}){
 const [phone,setPhone]=useState(order.phone),[comment,setComment]=useState(order.comment||''),[dueAt,setDueAt]=useState(order.dueAt||'')
 return <div className="modal-backdrop"><div className="payment-modal compact-modal"><header><h2>Изменить заказ</h2><button onClick={close}>×</button></header><label className="cash-input"><span>Телефон</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="cash-input"><span>Описание заказа</span><textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label className="cash-input"><span>Срок готовности</span><input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><button className="primary confirm" disabled={phone.replace(/\D/g,'').length<5||!comment.trim()||!dueAt} onClick={async()=>{await window.raspechatkaPos.updateOrder({id:order.id,phone,comment,dueAt});await saved()}}>Сохранить</button></div></div>
}
function CreateOrder({close,saved}:{close:()=>void;saved:()=>Promise<void>}){
 const [sales,setSales]=useState<SaleSummary[]>([]),[query,setQuery]=useState(''),[saleId,setSaleId]=useState(''),[phone,setPhone]=useState(''),[comment,setComment]=useState(''),[dueAt,setDueAt]=useState(''),[error,setError]=useState('')
 const load=async()=>{try{setSales((await window.raspechatkaPos.listSales()).filter(s=>s.status!=='returned'))}catch(e){setError(String(e))}}
 const matches=sales.filter(s=>(s.receiptNumber+' '+(s.customerName||'')+' '+(s.customerPhone||'')).toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).slice(0,20)
 return <div className="modal-backdrop"><div className="payment-modal order-create-modal"><header><h2>Создать заказ</h2><button onClick={close}>×</button></header><button onClick={()=>void load()}>Загрузить оплаченные чеки</button><input className="order-receipt-search" placeholder="Номер, телефон или покупатель" value={query} onChange={e=>setQuery(e.target.value)}/><select value={saleId} onChange={e=>{setSaleId(e.target.value);const s=sales.find(x=>x.id===e.target.value);if(s){setPhone(s.customerPhone||'')}}}><option value="">Выберите чек</option>{matches.map(s=><option key={s.id} value={s.id}>{s.receiptNumber} · {s.customerName||'Покупатель'} · {money(s.totalMinor)}</option>)}</select><label className="cash-input"><span>Телефон</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="cash-input"><span>Описание заказа</span><textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label className="cash-input"><span>Срок готовности</span><input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label>{error&&<div className="error-note">{error}</div>}<button className="primary confirm" disabled={!saleId||phone.replace(/\D/g,'').length<5||!comment.trim()||!dueAt} onClick={async()=>{try{await window.raspechatkaPos.createOrderFromSale({saleId,phone,comment,dueAt});await saved()}catch(e){setError(e instanceof Error?e.message:String(e))}}}>Создать</button></div></div>
}
