import { useEffect, useMemo, useState } from 'react'
import type { BootState, HeldReceipt, PointReceiptSummary, ReceiptSearchFilters, ReturnSummary, SaleDetails, SaleSummary } from '../../shared/contracts'
import { formatPersonShortName } from './person-name'

const money=(minor:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(minor/100)
const paymentNames:Record<string,string>={cash:'Наличные',card:'Карта',qr:'Безналичные',remote_payment:'Безналичные',mixed:'Смешанная'}
const defaultFilters:ReceiptSearchFilters={period:'current_shift',paymentChannel:''}

type Props={boot:BootState;sales:SaleSummary[];held:HeldReceipt[];returns:ReturnSummary[];onPrint:(id:string,kind:'fiscal-copy'|'commodity')=>Promise<void>;onReturn:(sale:SaleSummary)=>Promise<void>;onRestore:(receipt:HeldReceipt)=>Promise<void>;onRefresh:()=>Promise<void>;notify:(text:string)=>void}

const rubles=(value:string)=>{if(!value.trim())return undefined;const n=Number(value.replace(',','.'));return Number.isFinite(n)?Math.max(0,Math.round(n*100)):undefined}
const localMatch=(sale:SaleSummary,text:string)=>{const q=text.trim().toLocaleLowerCase('ru');if(!q)return true;return [sale.receiptNumber,sale.customerName||'',paymentNames[sale.paymentMethod]||sale.paymentMethod,new Date(sale.createdAt).toLocaleString('ru-RU')].join(' ').toLocaleLowerCase('ru').includes(q)}
const channelMatch=(sale:SaleSummary,channel:ReceiptSearchFilters['paymentChannel'])=>!channel||channel==='Cash'&&sale.paymentMethod==='cash'||channel==='Noncash'&&sale.paymentMethod!=='cash'
const dateMatch=(sale:SaleSummary,filters:ReceiptSearchFilters)=>{const t=new Date(sale.createdAt).getTime();const now=new Date();const day=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();if(filters.period==='today')return t>=day;if(filters.period==='yesterday')return t>=day-86400000&&t<day;if(filters.period==='7d')return t>=day-6*86400000;if(filters.period==='30d')return t>=day-29*86400000;if(filters.period==='custom'){const from=filters.dateFrom?new Date(filters.dateFrom+'T00:00:00').getTime():-Infinity;const to=filters.dateTo?new Date(filters.dateTo+'T23:59:59').getTime():Infinity;return t>=from&&t<=to}return true}

export default function ReceiptsPage({boot,sales,held,returns,onPrint,onReturn,onRestore,onRefresh,notify}:Props){
 const [draft,setDraft]=useState({text:'',period:'current_shift' as ReceiptSearchFilters['period'],from:'',to:'',cashier:'',channel:'' as ReceiptSearchFilters['paymentChannel'],min:'',max:''})
 const [applied,setApplied]=useState<ReceiptSearchFilters>(defaultFilters)
 const [rows,setRows]=useState<Array<SaleSummary|PointReceiptSummary>>(sales)
 const [online,setOnline]=useState(false);const [details,setDetails]=useState<SaleDetails|null>(null);const [message,setMessage]=useState('')
 const search=async(next=applied)=>{try{const result=await window.raspechatkaPos.searchPointReceipts(draft.text,next);setRows(result);setOnline(true);setMessage('')}catch{setOnline(false);setRows(sales.filter(s=>localMatch(s,draft.text)&&dateMatch(s,next)&&channelMatch(s,next.paymentChannel)&&(!next.amountMinMinor||s.totalMinor>=next.amountMinMinor)&&(!next.amountMaxMinor||s.totalMinor<=next.amountMaxMinor)&&(!next.cashierId||false)));setMessage('Нет связи с OS · показан локальный кэш текущей точки')}} 
 useEffect(()=>{setRows(sales)},[sales])
 const apply=()=>{const next:ReceiptSearchFilters={period:draft.period,shiftExternalId:boot.shift?.id,dateFrom:draft.period==='custom'?draft.from:undefined,dateTo:draft.period==='custom'?draft.to:undefined,cashierId:draft.cashier||undefined,amountMinMinor:rubles(draft.min),amountMaxMinor:rubles(draft.max),paymentChannel:draft.channel};setApplied(next);void search(next)}
 const clear=()=>{setDraft({text:'',period:'current_shift',from:'',to:'',cashier:'',channel:'',min:'',max:''});const next={...defaultFilters,shiftExternalId:boot.shift?.id};setApplied(next);void window.raspechatkaPos.searchPointReceipts('',next).then(result=>{setRows(result);setOnline(true)}).catch(()=>{setRows(sales);setOnline(false)})}
 const shown=useMemo(()=>rows,[rows])
 const open=async(row:SaleSummary|PointReceiptSummary)=>{try{setDetails(await window.raspechatkaPos.getSale(row.id))}catch{setMessage('Детали доступны только для локального снимка чека')}}
 const sale=(row:SaleSummary|PointReceiptSummary):SaleSummary=>('source' in row?row:{id:row.id,receiptNumber:row.receiptNumber,totalMinor:row.totalMinor,returnedMinor:0,paymentMethod:row.paymentLabel==='Наличные'?'cash':'card',customerName:row.customerName,createdAt:row.createdAt,status:row.status==='returned'?'returned':'completed',source:'server',returnable:false})
 return <Page title="Чеки">
  <div className="receipt-search-page"><form onSubmit={e=>{e.preventDefault();apply()}}><input value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder="Номер, фискальный номер, покупатель, телефон или товар"/><div className="receipt-periods">{(['current_shift','today','yesterday','7d','30d','custom'] as const).map(p=><button type="button" key={p} className={draft.period===p?'active':''} onClick={()=>setDraft({...draft,period:p})}>{({current_shift:'Текущая смена',today:'Сегодня',yesterday:'Вчера','7d':'7 дней','30d':'30 дней',custom:'Период'} as Record<string,string>)[p]}</button>)}</div>{draft.period==='custom'&&<div className="receipt-filter-grid"><label>Дата с<input type="date" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>Дата по<input type="date" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></label></div>}<div className="receipt-filter-grid"><label>Кассир<select value={draft.cashier} onChange={e=>setDraft({...draft,cashier:e.target.value})}><option value="">Все кассиры</option>{boot.employees.map(e=><option key={e.id} value={e.id}>{formatPersonShortName(e.name)}</option>)}</select></label><label>Оплата<select value={draft.channel} onChange={e=>setDraft({...draft,channel:e.target.value as ReceiptSearchFilters['paymentChannel']})}><option value="">Любая</option><option value="Cash">Наличные</option><option value="Noncash">Безналичные</option></select></label><label>Сумма от<input inputMode="decimal" value={draft.min} onChange={e=>setDraft({...draft,min:e.target.value})}/></label><label>Сумма до<input inputMode="decimal" value={draft.max} onChange={e=>setDraft({...draft,max:e.target.value})}/></label><button type="submit" className="primary">Найти</button><button type="button" onClick={clear}>Очистить</button></div></form></div>
  {online?null:<div className="receipt-cache-note">Локальный кэш текущей точки</div>}
  {held.length>0&&<section className="held"><h3>Отложенные</h3>{held.map(r=><article key={r.id}><div><b>{r.customer?.name||r.label}</b><small>{money(r.totalMinor??r.lines.reduce((n,l)=>n+Math.round(l.quantity*l.unitPriceMinor),0))} · {r.lines.length} поз. · {new Date(r.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small><small>{r.lines.slice(0,4).map(l=>l.name+' × '+l.quantity).join(' · ')}{r.lines.length>4?' · + ещё '+(r.lines.length-4):''}</small></div><button onClick={()=>void onRestore(r)}>Продолжить</button></article>)}</section>}
  <div className="data-table receipts-table"><header><span>Чек</span><span>Дата/время</span><span>Кассир</span><span>Покупатель</span><span>Оплата</span><span>Сумма/статус</span><span>Действия</span></header>{shown.length?shown.map(row=>{const s=sale(row);const server=s.source==='server';const reason=server?'Межкассовый возврат требует центрального резервирования':s.returnable===false?'Чек уже полностью возвращён':undefined;return <div key={row.id} onClick={()=>void open(row)}><b>{s.receiptNumber}</b><span>{new Date(s.createdAt).toLocaleString('ru-RU')}</span><span>{'cashierName' in row?row.cashierName||'—':'—'}</span><span>{s.customerName||'Розничный покупатель'}</span><span>{paymentNames[s.paymentMethod]||s.paymentMethod}</span><strong>{money(s.totalMinor)}<small>{s.status}</small></strong><div className="sale-actions" onClick={e=>e.stopPropagation()}><button onClick={()=>void onPrint(s.id,'commodity')}>Товарный чек</button><button disabled={server} title={server?'Точная копия server-only чека недоступна':'Фискальная копия недоступна без точного документа'} onClick={()=>void onPrint(s.id,'fiscal-copy')}>Копия чека</button><button disabled={Boolean(reason)||!boot.shift} title={reason||(!boot.shift?'Откройте смену для возврата':'')} onClick={()=>void onReturn(s)}>Возврат</button></div></div>}) : <div className="page-empty">Чеки не найдены</div>}</div>
  {details&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDetails(null)}}><section className="payment-modal receipt-detail-modal"><header><div><small>ЧЕК</small><h2>{details.receiptNumber}</h2></div><button onClick={()=>setDetails(null)}>×</button></header><div className="receipt-detail-summary"><div><small>Дата/время</small><b>{new Date(details.createdAt).toLocaleString('ru-RU')}</b></div><div><small>Покупатель/телефон</small><b>{details.customerName||'Розничный покупатель'}</b></div><div><small>Оплата</small><b>{details.payments.map(p=>paymentNames[p.method]||p.method).join(' + ')}</b></div><div><small>Итого</small><strong>{money(details.totalMinor)}</strong></div></div><div className="receipt-detail-lines">{details.lines.map(l=><article key={l.id}><div><b>{l.name}</b><small>{l.quantity} × {money(l.unitPriceMinor)} · строка {money(Math.round(l.quantity*l.unitPriceMinor*(1-(l.discountPercent||0)/100)))}</small></div>{l.returnedQuantity>0&&<span>Возвращено: {l.returnedQuantity}</span>}</article>)}</div></section></div>}
  {message&&<div className="pilot-message">{message}</div>}
 </Page>
}
function Page({title,children}:{title:string;children:React.ReactNode}){return <main className="page"><div className="page-heading"><h1>{title}</h1></div>{children}</main>}
