import { useState } from 'react'
import type {
  DeliveryNotice, OperationalCatalogItem, Product, StockReceiptRequest, StockWriteOffRequest,
  SupplyRequestInput, WorkplaceData, WorkScheduleEntry,
} from '../../shared/contracts'
import { formatMoney } from './money'
import './workplace.css'

export type ReceiveLineDraft={purchaseOrderItemId:string;itemName:string;uom:string;remainingQuantity:number;quantity:number}
export const operationalStockItems=(catalog:OperationalCatalogItem[])=>catalog.filter((item)=>item.trackInventory&&['Product','Variant'].includes(item.itemType))
export const warehouseItemMatches=(item:OperationalCatalogItem,query:string)=>{
  const needle=query.trim().toLocaleLowerCase()
  return !needle||[item.name,item.id,item.itemCode].some((value)=>value.toLocaleLowerCase().includes(needle))
}
export const buildStockReceiptRequest=(purchaseOrderId:string,lines:ReceiveLineDraft[]):StockReceiptRequest=>({
  purchaseOrderId,
  lines:lines
    .filter((line)=>Number.isFinite(line.quantity)&&line.quantity>0&&line.quantity<=line.remainingQuantity)
    .map((line)=>({purchaseOrderItemId:line.purchaseOrderItemId,quantity:line.quantity})),
})

export const shiftDisplayLabel=(shiftCode?:string,shiftName?:string)=>{
  const code=shiftCode?.trim().toUpperCase()
  return code==='U'?'У':code==='V'?'В':shiftCode?.trim()||shiftName||'—'
}

export const scheduleCellPresentation=(entries:Array<Pick<WorkScheduleEntry,'shiftCode'|'shiftName'>>)=>{
  const codes=new Set(entries.map((entry)=>entry.shiftCode?.trim().toUpperCase()).filter(Boolean))
  if(codes.has('U')&&codes.has('V'))return {label:'У/В',className:'schedule-mark schedule-shift-both'}
  const labels=[...new Set(entries.map((entry)=>shiftDisplayLabel(entry.shiftCode,entry.shiftName)))]
  if(codes.size===1&&codes.has('U'))return {label:'У',className:'schedule-mark schedule-shift-morning'}
  if(codes.size===1&&codes.has('V'))return {label:'В',className:'schedule-mark schedule-shift-evening'}
  return {label:labels.join(' · ')||'—',className:entries.length?'schedule-mark schedule-shift-other':''}
}

type WorkPageProps={
  products:Product[]
  data:WorkplaceData
  shiftOpen:boolean
  onChanged:()=>Promise<void>
  notify:(text:string)=>void
}

export default function WorkPage({products:_products,data,shiftOpen,onChanged,notify}:WorkPageProps){
  const [tab,setTab]=useState<'schedule'|'stock'|'cleaner'>('schedule')
  const scheduleMonth=data.scheduleMonth;const days=Array.from({length:scheduleMonth.days||0},(_,index)=>index+1)
  const monthLabel=scheduleMonth.month?new Date(scheduleMonth.month+'-01T00:00:00').toLocaleDateString('ru-RU',{month:'long',year:'numeric'}):'Текущий месяц'
  const gridColumns='minmax(180px,1fr) repeat('+days.length+',minmax(38px,1fr)) 76px'
  const entriesFor=(employeeId:string,day:number)=>scheduleMonth.entries.filter((entry)=>entry.employeeId===employeeId&&Number(entry.date.slice(-2))===day)
  return <main className="page"><div className="page-heading"><div><h1>Рабочее место</h1></div></div><div className="work-tabs"><button className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}>График работы</button><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Товары и склад</button><button className={tab==='cleaner'?'active':''} onClick={()=>setTab('cleaner')}>Уборка{data.cleaner.paymentDueMinor>0&&<b>!</b>}</button></div>
    {tab==='schedule'&&<div className="work-schedule"><section className="work-card schedule-month"><header><div><h3>График точки</h3><p>{monthLabel}</p></div><small>Только просмотр</small></header>{days.length>0&&scheduleMonth.employees.length?<div className="schedule-grid-scroll"><div className="schedule-grid"><div className="schedule-grid-row schedule-grid-header" style={{gridTemplateColumns:gridColumns}}><strong>Сотрудник</strong>{days.map((day)=>{const date=new Date(scheduleMonth.month+'-'+String(day).padStart(2,'0')+'T00:00:00');return <span key={day}>{date.toLocaleDateString('ru-RU',{weekday:'short'}).replace('.','')}<b>{day}</b></span>})}<strong>Часы</strong></div>{scheduleMonth.employees.map((employee)=>{const entries=days.map((day)=>entriesFor(employee.id,day));const hours=entries.flat().reduce((sum,entry)=>sum+entry.plannedHours,0);return <div className="schedule-grid-row" key={employee.id} style={{gridTemplateColumns:gridColumns}}><strong>{employee.name}</strong>{entries.map((dayEntries,dayIndex)=>{const presentation=scheduleCellPresentation(dayEntries);const title=dayEntries.map((entry)=>entry.shiftName+' · '+entry.startTime.slice(0,5)+'–'+entry.endTime.slice(0,5)).join(' | ');return <span key={dayIndex} className={presentation.className} title={dayEntries.length?title:undefined}>{presentation.label}</span>})}<b>{hours} ч.</b></div>})}</div></div>:<p>Опубликованный график точки пока не загружен.</p>}</section><section className="work-card schedule-upcoming"><h3>Мои ближайшие 5 смен</h3>{data.myUpcomingShifts.length?data.myUpcomingShifts.map((entry)=><article key={entry.id}><div><b>{new Date(entry.date+'T00:00:00').toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'})}</b><small>{shiftDisplayLabel(entry.shiftCode,entry.shiftName)}</small></div><strong>{entry.startTime.slice(0,5)}–{entry.endTime.slice(0,5)} · {entry.plannedHours} ч.</strong></article>):<p>Ближайших опубликованных смен нет.</p>}</section></div>}
    {tab==='stock'&&<WarehouseWorkspace data={data} onChanged={onChanged} notify={notify}/>}
    {tab==='cleaner'&&<div className="work-grid"><section className="work-card hero-card"><small>УБОРОК ДО ВЫПЛАТЫ</small><h2>{Math.min(data.cleaner.visitsSincePayment,4)} из 4</h2><p>Каждое посещение отмечается один раз.</p><button className="primary" onClick={async()=>{try{const r=await window.raspechatkaPos.recordCleanerVisit();await onChanged();notify(r.paymentDueMinor?'Четыре уборки отмечены — можно выплатить 2 000 ₽':'Посещение уборщицы отмечено')}catch(e){notify(String(e))}}}>Отметить сегодняшнюю уборку</button>{data.cleaner.paymentDueMinor>0&&<button className="pay-cleaner" disabled={!shiftOpen} onClick={async()=>{try{await window.raspechatkaPos.payCleaner(data.cleaner.paymentDueMinor);await onChanged();notify('Выплата уборщице проведена как изъятие из кассы')}catch(e){notify(e instanceof Error?e.message:String(e))}}}>Выплатить {formatMoney(data.cleaner.paymentDueMinor)} из кассы</button>}</section><section className="work-card"><h3>Последние посещения</h3>{data.cleaner.recentVisits.length?data.cleaner.recentVisits.map((x)=><article key={x.id}><div><b>{new Date(x.visitDate+'T00:00:00').toLocaleDateString('ru-RU')}</b><small>{x.recordedBy}</small></div><span>{x.paid?'Оплачено':'Ожидает'}</span></article>):<p>Посещений пока нет</p>}</section></div>}
  </main>
}

export function WarehouseWorkspace({data,onChanged,notify}:{data:WorkplaceData;onChanged:()=>Promise<void>;notify:(text:string)=>void}){
  const [writeOff,setWriteOff]=useState(false);const [need,setNeed]=useState(false);const [receiveOrder,setReceiveOrder]=useState<DeliveryNotice|null>(null)
  const [expanded,setExpanded]=useState<Record<string,boolean>>({});const [stockQuery,setStockQuery]=useState('')
  const catalog=data.operationalCatalog||[];const stockProducts=operationalStockItems(catalog)
  const stockRows=stockProducts.filter((item)=>warehouseItemMatches(item,stockQuery))
  return <div className="warehouse-workspace">
    <div className="work-toolbar warehouse-actions" data-workplace-block="actions"><div><h2>Товары и склад</h2><p>Остатки и поставки текущей точки.</p></div><button onClick={()=>setWriteOff(true)}>Списать брак</button><button className="primary" onClick={()=>setNeed(true)}>Потребность точки</button></div>
    <section className="work-card delivery-list warehouse-deliveries" data-workplace-block="deliveries"><header><h2>Поставки</h2><small>Открытые заказы текущей точки</small></header>{data.deliveries.length?data.deliveries.map((order)=><DeliveryCard key={order.id} order={order} expanded={Boolean(expanded[order.id])} onToggle={()=>setExpanded({...expanded,[order.id]:!expanded[order.id]})} onReceive={()=>setReceiveOrder(order)}/>):<WorkEmpty title="Поставок нет" text="Открытые заказы появятся здесь из OS."/ >}</section>
    <section className="work-card stock-list warehouse-stock" data-workplace-block="stock"><label className="warehouse-search"><span>Поиск</span><input value={stockQuery} onChange={(e)=>setStockQuery(e.target.value)} placeholder="Название, ID или код"/></label><div className="stock-table-scroll"><header><span>Товар</span><span>Остаток</span><span>Где лежит</span></header>{stockRows.length?stockRows.map((item)=><div key={item.id}><div><b>{item.name}</b><small>{item.itemCode||item.id}</small></div><strong className={(item.stock??0)<=0?'low':''}>{item.stock??'—'} {item.uom}</strong><span>{item.storageAddress||'Адрес ещё не указан'}</span></div>):<p>Складские позиции не найдены.</p>}</div></section>
    {writeOff&&<WriteOffModal products={stockProducts} onClose={()=>setWriteOff(false)} onComplete={async(request)=>{try{await window.raspechatkaPos.reportStockWriteOff(request);setWriteOff(false);await onChanged();notify('Списание поставлено в очередь и уйдёт в OS при синхронизации')}catch(e){notify(e instanceof Error?e.message:String(e))}}}/>}
    {need&&<SupplyRequestModal products={catalog} onClose={()=>setNeed(false)} onComplete={async(request)=>{try{await window.raspechatkaPos.createSupplyRequest(request);setNeed(false);await onChanged();notify('Потребность точки сохранена на кассе и будет передана в OS при синхронизации')}catch(e){notify(e instanceof Error?e.message:String(e))}}}/>}
    {receiveOrder&&<ReceiveModal order={receiveOrder} onClose={()=>setReceiveOrder(null)} onComplete={async(request)=>{try{await window.raspechatkaPos.createStockReceipt(request);setReceiveOrder(null);await onChanged();notify('Приёмка сохранена на кассе и будет передана в OS при синхронизации')}catch(e){notify(e instanceof Error?e.message:String(e))}}}/>}
  </div>
}

function WorkEmpty({title,text}:{title:string;text:string}){return <div className="page-empty"><i>＋</i><b>{title}</b><span>{text}</span></div>}

function DeliveryCard({order,expanded,onToggle,onReceive}:{order:DeliveryNotice;expanded:boolean;onToggle:()=>void;onReceive:()=>void}){return <article className="delivery-card"><button className="delivery-summary" onClick={onToggle}><div><b>№ {order.id}</b><strong>{order.supplier}</strong><small>{order.expectedDate?new Date(order.expectedDate+'T00:00:00').toLocaleDateString('ru-RU'):'Дата не назначена'} · {order.status}</small></div><span>{order.comment||order.receivingNote||order.details||'Без комментария'}</span></button>{expanded&&<div className="delivery-detail">{order.items.filter((item)=>item.remainingQuantity>0).map((item)=><div key={item.purchaseOrderItemId}><span>{item.itemName} · {item.itemCode||item.itemId}</span><b>{item.remainingQuantity} {item.uom}</b></div>)}{order.items.some((item)=>item.remainingQuantity>0)&&<button className="primary" onClick={onReceive}>Создать приёмку</button>}</div>}</article>}

export function WriteOffModal({products,onClose,onComplete}:{products:OperationalCatalogItem[];onClose:()=>void;onComplete:(request:StockWriteOffRequest)=>Promise<void>}){const [productId,setProductId]=useState(products[0]?.id||'');const [quantity,setQuantity]=useState('1');const [reason,setReason]=useState<StockWriteOffRequest['reason']>('Брак');const [comment,setComment]=useState('');return <div className="modal-backdrop"><div className="payment-modal compact-modal"><header><div><small>СКЛАД ТОЧКИ</small><h2>Списать товар</h2></div><button onClick={onClose}>×</button></header><label className="cash-input"><span>Товар</span><select value={productId} onChange={(e)=>setProductId(e.target.value)}>{products.map((x)=><option key={x.id} value={x.id}>{x.name} · остаток {x.stock??0}</option>)}</select></label><label className="cash-input"><span>Количество</span><input type="number" min="0.001" step="0.001" value={quantity} onChange={(e)=>setQuantity(e.target.value)}/></label><label className="cash-input"><span>Причина</span><select value={reason} onChange={(e)=>setReason(e.target.value as StockWriteOffRequest['reason'])}><option>Брак</option><option>Внутренние нужды</option><option>Обучение</option><option>Другое</option></select></label><label className="cash-input"><span>Комментарий</span><input value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Что произошло — коротко"/></label><button className="primary confirm" disabled={!productId||Number(quantity)<=0} onClick={()=>onComplete({productId,quantity:Number(quantity),reason,comment})}>Подтвердить списание</button></div></div>}

export function SupplyRequestModal({products,onClose,onComplete}:{products:OperationalCatalogItem[];onClose:()=>void;onComplete:(request:SupplyRequestInput)=>Promise<void>}){const [productId,setProductId]=useState('');const [itemName,setItemName]=useState('');const [quantity,setQuantity]=useState('1');const [comment,setComment]=useState('');const select=(id:string)=>{setProductId(id);setItemName(products.find((x)=>x.id===id)?.name||'')};return <div className="modal-backdrop"><div className="payment-modal compact-modal"><header><div><small>ПОТРЕБНОСТЬ ТОЧКИ</small><h2>Что нужно заказать</h2></div><button onClick={onClose}>×</button></header><label className="cash-input"><span>Из каталога</span><select value={productId} onChange={(e)=>select(e.target.value)}><option value="">Другая позиция</option>{products.map((x)=><option key={x.id} value={x.id}>{x.name} · {x.itemCode||x.id}</option>)}</select></label><label className="cash-input"><span>Наименование</span><input value={itemName} onChange={(e)=>setItemName(e.target.value)} placeholder="Например: бумага А4"/></label><label className="cash-input"><span>Количество</span><input type="number" min="0.001" step="0.001" value={quantity} onChange={(e)=>setQuantity(e.target.value)}/></label><label className="cash-input"><span>Комментарий</span><input value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Срочность или уточнение"/></label><button className="primary confirm" disabled={!itemName.trim()||Number(quantity)<=0} onClick={()=>onComplete({productId:productId||undefined,itemName:itemName.trim(),quantity:Number(quantity),comment})}>Отправить закупщику</button></div></div>}

export function ReceiveModal({order,onClose,onComplete}:{order:DeliveryNotice;onClose:()=>void;onComplete:(request:StockReceiptRequest)=>Promise<void>}){const [lines,setLines]=useState<ReceiveLineDraft[]>(()=>order.items.filter((item)=>item.remainingQuantity>0).map((item)=>({purchaseOrderItemId:item.purchaseOrderItemId,itemName:item.itemName,uom:item.uom,remainingQuantity:item.remainingQuantity,quantity:item.remainingQuantity})));const update=(id:string,quantity:number)=>setLines((current)=>current.map((line)=>line.purchaseOrderItemId===id?{...line,quantity}:line));const invalid=lines.some((line)=>!Number.isFinite(line.quantity)||line.quantity<0||line.quantity>line.remainingQuantity);const request=buildStockReceiptRequest(order.id,lines);return <div className="modal-backdrop"><div className="payment-modal compact-modal"><header><div><small>ПРИЁМКА ПОСТАВКИ</small><h2>№ {order.id}</h2></div><button onClick={onClose}>×</button></header>{lines.length?lines.map((line)=><div className="receive-line" key={line.purchaseOrderItemId}><div><b>{line.itemName}</b><small>Остаток: {line.remainingQuantity} {line.uom}</small></div><input type="number" min="0" max={line.remainingQuantity} step="0.001" value={line.quantity} onChange={(e)=>update(line.purchaseOrderItemId,Number(e.target.value))}/><button title="Убрать строку" onClick={()=>setLines((current)=>current.filter((x)=>x.purchaseOrderItemId!==line.purchaseOrderItemId))}>×</button></div>):<p>Нет строк для приёмки.</p>}{invalid&&<div className="error-note">Количество не может превышать остаток по заказу.</div>}<button className="primary confirm" disabled={invalid||request.lines.length===0} onClick={()=>onComplete(request)}>Подтвердить приёмку</button></div></div>}
