<script setup>
import { onMounted, ref } from "vue";
import { call } from "../api";
const loading=ref(true),saving=ref(false),error=ref(""),areas=ref([]),roles=ref([]),matrix=ref({});
const roleLabels={"Raspechatka Network Admin":"Администратор сети","Raspechatka Franchise Owner":"Владелец франчайзи","Raspechatka Point Manager":"Управляющий точками","Raspechatka Cashier":"Кассир"};
async function load(){loading.value=true;try{const r=await call("raspechatka.access.get_access_settings");areas.value=r.areas;roles.value=r.roles;const m={};for(const role of roles.value){m[role]={};for(const area of areas.value)m[role][area.name]="None";}for(const rule of r.rules)m[rule.role][rule.access_area]=rule.access_level;matrix.value=m;}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function save(){saving.value=true;error.value="";try{const rules=[];for(const role of roles.value)for(const area of areas.value)rules.push({role,access_area:area.name,access_level:matrix.value[role][area.name]});await call("raspechatka.access.save_access_settings",{rules:JSON.stringify(rules)},{method:"POST"});}catch(e){error.value=e.message;}finally{saving.value=false;}}
onMounted(load);
</script>
<template><section class="page access-page"><div class="page-heading"><div><div class="eyebrow">НАСТРОЙКИ</div><h1>Права доступа</h1><p>Какие разделы доступны каждой роли сотрудников</p></div><button class="button button-primary" :disabled="saving" @click="save">{{saving?'Сохраняем…':'Сохранить настройки'}}</button></div><div v-if="error" class="form-error">{{error}}</div><div v-if="loading" class="table-message"><span class="loader"></span></div><div v-else class="access-matrix table-shell"><table><thead><tr><th>Раздел программы</th><th v-for="role in roles" :key="role">{{roleLabels[role]}}</th></tr></thead><tbody><tr v-for="area in areas" :key="area.name"><td class="item-name">{{area.area_name}}</td><td v-for="role in roles" :key="role"><select v-model="matrix[role][area.name]" :disabled="role==='Raspechatka Network Admin'&&area.area_code==='settings.access'"><option value="None">Нет доступа</option><option value="View">Просмотр</option><option value="Edit">Изменение</option><option value="Admin">Полный доступ</option></select></td></tr></tbody></table></div><p class="settings-note">Назначенные сотруднику точки дополнительно ограничивают данные внутри доступного раздела.</p></section></template>
