<script setup>
import { computed,onMounted,reactive,ref,watch } from "vue";
import { useRoute } from "vue-router";
import { call,canAccess } from "../api";
import AppModal from "../components/AppModal.vue";
import ReferenceTable from "../components/ReferenceTable.vue";
import ListPageHeader from "../components/ListPageHeader.vue";
import SmartFilterBar from "../components/SmartFilterBar.vue";
const route=useRoute(),kind=computed(()=>route.meta.kind),rows=ref([]),loading=ref(true),error=ref(""),filters=ref({search:""}),detail=ref(null),saving=ref(false),formError=ref("");const form=reactive({}),options=reactive({points:[],segments:[],occasions:[],promo_codes:[]});
const configs={
segments:{title:"Сегменты",description:"Динамические аудитории клиентов для будущих рассылок",create:"Создать сегмент",area:"clients.marketing",columns:cols(["segment_name","Сегмент",1],["audience_count","Клиентов"],["business_point","Точка"],["club_status","Статус клуба"],["minimum_active_channels","Каналов"],["active","Активен"]),fields:[f("segment_name","Название","text",1),f("business_point","Точка регистрации","link",0,"points"),f("club_status","Статус клуба","select",0,["","Регистрация","Ожидает мессенджер","Активен","Заблокирован"]),f("minimum_discount_percent","Минимальная скидка, %","number"),f("minimum_active_channels","Минимум активных каналов","number"),f("birthday_days_ahead","День рождения в ближайшие, дней","number"),f("registered_from","Зарегистрирован с","date"),f("registered_to","Зарегистрирован по","date"),f("marketing_consent_only","Только с согласием на рекламу","check"),f("notes","Комментарий","textarea")]},
campaigns:{title:"Рассылки",description:"Подготовка аудитории, сообщения и отслеживание покупок по промокоду",create:"Создать рассылку",area:"clients.marketing",columns:cols(["campaign_name","Рассылка",1],["status","Статус"],["segment","Сегмент"],["channel","Канал"],["planned_at","План"],["sent_count","Отправлено"],["purchase_count","Покупок"],["revenue","Выручка"]),fields:[f("campaign_name","Название","text",1),f("status","Статус","select",1,["Черновик","Запланирована","Отправляется","Завершена","Отменена"]),f("segment","Сегмент","link",1,"segments"),f("occasion","Повод","link",0,"occasions"),f("channel","Канал","select",1,["Telegram","MAX","VK","По доступным каналам"]),f("planned_at","Плановая дата","datetime-local"),f("promo_code","Промокод","link",0,"promo_codes"),f("message_text","Текст сообщения","textarea"),f("notes","Комментарий","textarea")]},
"promo-codes":{title:"Промокоды",description:"Коды для кассы и измерения конверсии рассылок",create:"Создать промокод",area:"clients.loyalty",columns:cols(["code","Промокод",1],["discount_type","Тип"],["discount_value","Скидка"],["valid_from","Действует с"],["valid_to","Действует по"],["uses_count","Использовано"],["active","Активен"]),fields:[f("code","Промокод","text",1),f("campaign","Рассылка","link",0,"campaigns"),f("discount_type","Тип скидки","select",1,["Процент","Сумма"]),f("discount_value","Размер скидки","number",1),f("valid_from","Действует с","datetime-local",1),f("valid_to","Действует по","datetime-local",1),f("maximum_uses","Максимум применений (0 — без лимита)","number"),f("one_use_per_client","Одно применение на клиента","check"),f("notes","Комментарий","textarea")]},
calendar:{title:"Календарь промо",description:"Праздники и события, к которым заранее готовятся рассылки",create:"Добавить событие",area:"clients.marketing",columns:cols(["occasion_name","Событие",1],["occasion_type","Тип"],["event_date","Дата"],["prepare_days_before","Подготовка, дней"],["recurring_annually","Ежегодно"],["active","Активно"]),fields:[f("occasion_name","Название","text",1),f("occasion_type","Тип","select",1,["Праздник","Акция","Событие"]),f("event_date","Дата","date",1),f("prepare_days_before","Начать подготовку за, дней","number"),f("recurring_annually","Повторять ежегодно","check"),f("notes","Комментарий","textarea")]}
};
function cols(...items){return items.map(([key,label,primary])=>({key,label,primary:!!primary}));}function f(key,label,type="text",required=0,values=null){return{key,label,type,required:!!required,values};}
const config=computed(()=>configs[kind.value]),canEdit=computed(()=>canAccess(config.value.area,"Edit"));
function reset(values={}){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,{active:1,marketing_consent_only:1,status:"Черновик",channel:"По доступным каналам",discount_type:"Процент",one_use_per_client:1,occasion_type:"Праздник",recurring_annually:1,prepare_days_before:14,...values});}
function fieldOptions(field){if(Array.isArray(field.values))return field.values.map(v=>({value:v,label:v||"Не выбрано"}));return (options[field.values]||[]).map(v=>({value:v.name,label:v.segment_name||v.campaign_name||v.occasion_name||v.code||v.point_name||v.name}));}
async function load(){loading.value=true;error.value="";try{rows.value=await call("raspechatka.api.clients.get_marketing_records",{kind:kind.value,search:filters.value.search});}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function loadOptions(){try{Object.assign(options,await call("raspechatka.api.clients.get_client_options"));options.campaigns=canAccess("clients.marketing")?await call("raspechatka.api.clients.get_marketing_records",{kind:"campaigns"}):[];}catch(e){error.value=e.message;}}
function create(){reset();detail.value={};formError.value="";}
async function open(row){try{const data=await call("raspechatka.api.clients.get_marketing_record",{kind:kind.value,name:row.name});detail.value=data;reset(JSON.parse(JSON.stringify(data)));}catch(e){error.value=e.message;}}
async function save(){saving.value=true;formError.value="";try{const r=await call("raspechatka.api.clients.save_marketing_record",{kind:kind.value,data:JSON.stringify(form)},{method:"POST"});await Promise.all([load(),loadOptions()]);await open({name:r.name});}catch(e){formError.value=e.message;}finally{saving.value=false;}}
function generateCode(){form.code=`RP${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
watch(kind,()=>{detail.value=null;filters.value={search:""};load();});onMounted(()=>Promise.all([load(),loadOptions()]));
</script>
<template><section class="page marketing-page"><ListPageHeader :title="config.title"><template #actions><button v-if="canEdit" class="button button-primary" @click="create">＋ {{config.create}}</button></template></ListPageHeader><SmartFilterBar v-model="filters" :key="kind" :fields="[{key:'search',label:'Поиск',placeholder:'Поиск по разделу',wide:true}]" :view-key="`clients.${kind}`" @apply="load" @reset="load" /><ReferenceTable :key="kind" :rows="rows" :columns="config.columns" :view-key="`clients.${kind}`" :loading="loading" :error="error" @open="open" @retry="load" />
<AppModal v-if="detail!==null" :title="config.title" wide @close="detail=null"><form class="editor-form" @submit.prevent="save"><div class="form-section"><h3>Основное</h3><div class="form-grid"><label v-for="field in config.fields" :key="field.key" :class="{'span-3':field.type==='textarea'}">{{field.label}}<textarea v-if="field.type==='textarea'" v-model="form[field.key]" rows="4"></textarea><select v-else-if="field.type==='select'||field.type==='link'" v-model="form[field.key]" :required="field.required"><option v-for="o in fieldOptions(field)" :key="o.value" :value="o.value">{{o.label}}</option></select><input v-else-if="field.type==='check'" v-model="form[field.key]" type="checkbox" :true-value="1" :false-value="0" /><div v-else-if="field.key==='code'" class="code-input"><input v-model="form[field.key]" required /><button type="button" class="button button-secondary" @click="generateCode">Создать</button></div><input v-else v-model="form[field.key]" :type="field.type" :required="field.required" /></label><label v-if="kind!=='campaigns'" class="check-field"><input v-model="form.active" type="checkbox" :true-value="1" :false-value="0" /> Активно</label></div></div>
<div v-if="kind==='segments'&&detail?.members" class="form-section"><h3>Аудитория · {{detail.members.length}}</h3><div class="compact-list segment-members"><div v-for="member in detail.members" :key="member.name"><b>{{member.client_name}}</b><span>{{member.phone}}</span><span>{{member.primary_channel||'без канала'}}</span></div></div></div><div v-if="kind==='campaigns'&&form.name" class="campaign-result"><div><small>АУДИТОРИЯ</small><b>{{form.audience_count||0}}</b></div><div><small>ОТПРАВЛЕНО</small><b>{{form.sent_count||0}}</b></div><div><small>ПОКУПОК</small><b>{{form.purchase_count||0}}</b></div><div><small>ВЫРУЧКА</small><b>{{Number(form.revenue||0).toLocaleString('ru-RU')}} ₽</b></div></div><p v-if="formError" class="form-error">{{formError}}</p></form><template #footer><div></div><div class="footer-actions"><button class="button button-secondary" @click="detail=null">Закрыть</button><button v-if="canEdit" class="button button-primary" :disabled="saving" @click="save">{{saving?'Сохраняем…':'Сохранить'}}</button></div></template></AppModal></section></template>
