<script setup>
import { onMounted, reactive, ref } from "vue";
import { call } from "../api";
import AppModal from "../components/AppModal.vue";
import ListPageHeader from "../components/ListPageHeader.vue";

const data = reactive({ connections: [], entities: [], review_operations: [], review_count: 0, configured: false, default_sync_interval_minutes: 15, callback_url: "" });
const error = ref(""), loading = ref(true), saving = ref(false), connectionOpen = ref(false);
const appForm = reactive({ client_id: "", client_secret: "", default_sync_interval_minutes: 15 });
const connectionForm = reactive({});
const money = (value) => new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB" }).format(Number(value || 0));

async function load() { loading.value = true; error.value = ""; try { Object.assign(data, await call("raspechatka.api.tochka.get_bank_settings")); appForm.default_sync_interval_minutes = data.default_sync_interval_minutes; } catch (e) { error.value = e.message; } finally { loading.value = false; } }
async function saveApp() { saving.value = true; try { await call("raspechatka.api.tochka.save_bank_settings", { data: JSON.stringify(appForm) }, { method: "POST" }); appForm.client_id = ""; appForm.client_secret = ""; await load(); } catch (e) { error.value = e.message; } finally { saving.value = false; } }
function openConnection() { Object.assign(connectionForm, { connection_name: "", business_entity: data.entities[0]?.name || "", enabled: 1, sync_mode: "Live", sync_interval_minutes: data.default_sync_interval_minutes, overlap_days: 2 }); connectionOpen.value = true; }
async function saveConnection() { saving.value = true; try { await call("raspechatka.api.tochka.save_connection", { data: JSON.stringify(connectionForm) }, { method: "POST" }); connectionOpen.value = false; await load(); } catch (e) { error.value = e.message; } finally { saving.value = false; } }
async function createConsent(row) { try { const result = await call("raspechatka.api.tochka.begin_oauth", { connection: row.name }, { method: "POST" }); await navigator.clipboard.writeText(result.url); alert("Персональная ссылка согласия скопирована. Отправьте её владельцу выбранного ИП."); await load(); } catch (e) { error.value = e.message; } }
async function copyLink(row) { await navigator.clipboard.writeText(row.oauth_url); alert("Ссылка согласия скопирована."); }
async function accounts(row) { try { const result = await call("raspechatka.api.tochka.refresh_accounts", { connection: row.name }, { method: "POST" }); alert(`Счетов получено: ${result.received}; сопоставлено с ИП: ${result.matched}.`); await load(); } catch (e) { error.value = e.message; } }
async function sync(row) { try { await call("raspechatka.api.tochka.sync_now", { connection: row.name }, { method: "POST" }); alert("Загрузка выписки поставлена в очередь."); } catch (e) { error.value = e.message; } }
onMounted(load);
</script>

<template>
 <section class="page finance-page">
  <ListPageHeader title="Настройки · Точка Банк" />
  <div class="bank-note"><b>Входящая интеграция</b><span>ОС получает выписки из Точка Банка. Отправка платежей в банк здесь не реализована.</span></div>
  <div v-if="loading" class="table-message"><span class="loader"></span><span>Загружаем настройки банка…</span></div>
  <template v-else>
   <article class="settings-card"><header><div><small>ОБЩАЯ НАСТРОЙКА СЕТИ</small><h2>Приложение Распечатка ОС</h2></div><span :class="{ready:data.configured}" class="status">{{data.configured ? "Настроено" : "Не настроено"}}</span></header><div class="form-grid"><label>Client ID<input v-model="appForm.client_id" type="password" placeholder="Не меняйте, если уже сохранён" autocomplete="off" /></label><label>Client Secret<input v-model="appForm.client_secret" type="password" placeholder="Не меняйте, если уже сохранён" autocomplete="off" /></label><label>Интервал по умолчанию, минут<input v-model.number="appForm.default_sync_interval_minutes" type="number" min="5" /></label><label class="span-2">Callback URL<input :value="data.callback_url" readonly /></label></div><p>Ключи принадлежат приложению сети и хранятся зашифрованно. Их не вводят и не видят партнёры.</p><button class="button button-primary" :disabled="saving" @click="saveApp">Сохранить настройку</button></article>
   <div class="section-title"><div><h2>Подключения ИП</h2><span>Для каждого ИП — отдельное согласие владельца, токены и банковские счета.</span></div><button class="button button-primary" :disabled="!data.configured" @click="openConnection">＋ Подключить ИП</button></div>
   <div class="connection-list"><article v-for="row in data.connections" :key="row.name"><div><small>{{row.business_entity}}</small><h3>{{row.connection_name}}</h3><p>Интервал: {{row.sync_interval_minutes || data.default_sync_interval_minutes}} мин · Последняя загрузка: {{row.last_sync_at || "ещё не было"}}</p><em v-if="row.error_message">{{row.error_message}}</em></div><span class="status" :class="{ready:row.status==='Connected', danger:row.status==='Error'}">{{row.status}}</span><div class="actions"><button v-if="row.status!=='Connected'" class="button button-secondary" @click="createConsent(row)">Создать ссылку согласия</button><button v-if="row.oauth_url" class="button button-secondary" @click="copyLink(row)">Копировать ссылку</button><button v-if="row.status==='Connected'" class="button button-secondary" @click="accounts(row)">Сопоставить счета</button><button v-if="row.status==='Connected'" class="button button-primary" @click="sync(row)">Загрузить выписку</button></div></article><p v-if="!data.connections.length" class="empty-connection">Подключений пока нет. Сначала заполните ключи приложения, затем выберите ИП.</p></div>
   <article v-if="data.review_count" class="review-card"><h2>Требуют ручной разбор</h2><p>Операции без правила сохранены и не потеряны. Они не попадают в платежи, пока не будут классифицированы.</p><div v-for="row in data.review_operations" :key="row.name" class="review-row"><span>{{row.business_entity}}</span><b>{{row.counterparty_name || "Без контрагента"}}</b><span>{{money(row.amount)}}</span><small>{{row.purpose}}</small></div></article>
  </template>
  <p v-if="error" class="form-error">{{error}}</p>
  <AppModal v-if="connectionOpen" title="Подключить ИП к Точка Банку" @close="connectionOpen=false"><div class="form-grid"><label class="span-2">Название подключения<input v-model="connectionForm.connection_name" placeholder="Будет сформировано автоматически" /></label><label class="span-2">ИП<select v-model="connectionForm.business_entity"><option v-for="item in data.entities" :key="item.name" :value="item.name">{{item.short_name}}</option></select></label><label>Интервал синхронизации, минут<input v-model.number="connectionForm.sync_interval_minutes" type="number" min="5" /></label><label>Повторно проверять дней<input v-model.number="connectionForm.overlap_days" type="number" min="1" /></label><label class="check-field"><input v-model="connectionForm.enabled" type="checkbox" :true-value="1" :false-value="0" /> Автосинхронизация</label><label>Режим<select v-model="connectionForm.sync_mode"><option value="Live">Рабочий</option><option value="Dry Run">Dry Run — без создания платежей</option></select></label></div><template #footer><span></span><button class="button button-primary" :disabled="saving" @click="saveConnection">Сохранить</button></template></AppModal>
 </section>
</template>

<style scoped>
.settings-card,.connection-list article,.review-card,.bank-note{padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--surface);margin-bottom:18px}.settings-card header,.section-title,.connection-list article{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.settings-card h2,.section-title h2,.review-card h2{margin:3px 0;font-size:19px}.settings-card header small,.connection-list small{color:var(--muted);font-size:10px;font-weight:700;letter-spacing:.08em}.settings-card p,.section-title span,.connection-list p,.bank-note span,.review-card p{color:var(--muted);font-size:13px}.settings-card .form-grid{margin:16px 0}.status{padding:5px 8px;border-radius:999px;background:var(--surface-subtle);font-size:11px;font-weight:700}.status.ready{background:var(--green-soft);color:var(--green-dark)}.status.danger{color:var(--danger)}.connection-list{display:grid;gap:10px}.connection-list article{margin:0}.connection-list h3{margin:3px 0;font-size:16px}.connection-list p{margin:5px 0}.connection-list em{display:block;color:var(--danger);font-size:12px;font-style:normal}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px}.empty-connection{padding:24px;text-align:center;color:var(--muted);border:1px dashed var(--border);border-radius:14px}.review-row{display:grid;grid-template-columns:140px 1fr auto 2fr;gap:12px;padding:10px 0;border-top:1px solid var(--border);font-size:13px}.review-row small{color:var(--muted)}.bank-note{display:grid;gap:4px;border-left:4px solid var(--green)}@media(max-width:800px){.settings-card header,.section-title,.connection-list article{flex-direction:column}.actions{justify-content:flex-start}.review-row{grid-template-columns:1fr}.section-title .button{width:100%}}
</style>
