<script setup>
import { computed,onMounted,reactive,ref,watch } from "vue";
import { call,canAccess } from "../api";
import AppModal from "../components/AppModal.vue";
const rows=ref([]),loading=ref(true),error=ref(""),editorOpen=ref(false),saving=ref(false),formError=ref("");
const options=reactive({entities:[],points:[],accounts:[],articles:[],payment_methods:[]});
const filters=reactive({from_date:new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),to_date:new Date().toISOString().slice(0,10),business_entity:"",business_point:"",direction:"",financial_article:"",status:"",search:""});
const form=reactive({}); const totals=reactive({income:0,expense:0,net:0}); let timer;
const canEdit=computed(()=>canAccess("finance.operations","Edit"));
const pointsFor=(entity)=>options.points.filter(row=>!entity||row.business_entity===entity);
const accountsFor=(entity)=>options.accounts.filter(row=>!entity||row.business_entity===entity);
const articlesFor=(direction)=>options.articles.filter(row=>!direction||direction==="Transfer"||row.article_type===(direction==="Income"?"Income":"Expense"));
const money=v=>`${new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₽`;
const date=v=>v?new Intl.DateTimeFormat("ru-RU").format(new Date(`${v}T00:00:00`)):"—";
async function load(){loading.value=true;error.value="";try{const r=await call("raspechatka.api.finance.get_payments",filters);rows.value=r.rows;Object.assign(totals,r.totals);}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function loadOptions(){try{Object.assign(options,await call("raspechatka.api.finance.get_finance_options"));}catch(e){error.value=e.message;}}
async function open(name=null,direction="Expense"){formError.value="";try{const doc=await call("raspechatka.api.finance.get_payment",{name,direction});Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,doc);editorOpen.value=true;}catch(e){error.value=e.message;}}
function onEntity(){if(!pointsFor(form.business_entity).some(x=>x.name===form.business_point))form.business_point="";if(!accountsFor(form.business_entity).some(x=>x.name===form.bank_account))form.bank_account="";}
async function save(submit=false){saving.value=true;formError.value="";try{const r=await call("raspechatka.api.finance.save_payment",{data:JSON.stringify(form),submit:submit?1:0},{method:"POST"});await load();if(submit)editorOpen.value=false;else await open(r.name);}catch(e){formError.value=e.message;}finally{saving.value=false;}}
async function cancel(){if(!confirm("Отменить проведённый платёж?"))return;try{await call("raspechatka.api.finance.cancel_payment",{name:form.name},{method:"POST"});editorOpen.value=false;await load();}catch(e){formError.value=e.message;}}
function reset(){Object.assign(filters,{business_entity:"",business_point:"",direction:"",financial_article:"",status:"",search:""});load();}
watch(()=>filters.search,()=>{clearTimeout(timer);timer=setTimeout(load,250)});onMounted(()=>Promise.all([loadOptions(),load()]));
</script>
<template><section class="page finance-page"><div class="page-heading"><div><div class="eyebrow">ФИНАНСЫ / ОПЕРАЦИИ</div><h1>Платежи</h1><p>Единый реестр всех приходов и расходов сети</p></div><div v-if="canEdit" class="heading-actions"><button class="button button-secondary" @click="open(null,'Income')">＋ Приход</button><button class="button button-primary" @click="open(null,'Expense')">＋ Расход</button></div></div>
<div class="finance-summary"><article><span>ПРИХОД</span><b>{{money(totals.income)}}</b></article><article><span>РАСХОД</span><b>{{money(totals.expense)}}</b></article><article :class="{accent:totals.net>=0}"><span>ДЕНЕЖНЫЙ ПОТОК</span><b>{{money(totals.net)}}</b></article></div>
<div class="finance-toolbar"><label class="search-field"><span>⌕</span><input v-model="filters.search" placeholder="Номер, контрагент или назначение" /></label><input v-model="filters.from_date" type="date" @change="load"/><input v-model="filters.to_date" type="date" @change="load"/><select v-model="filters.business_entity" @change="filters.business_point='';load()"><option value="">Все ИП</option><option v-for="x in options.entities" :key="x.name" :value="x.name">{{x.short_name}}</option></select><select v-model="filters.business_point" @change="load"><option value="">Все точки</option><option v-for="x in pointsFor(filters.business_entity)" :key="x.name" :value="x.name">{{x.point_name}}</option></select><select v-model="filters.direction" @change="load"><option value="">Все операции</option><option value="Income">Приход</option><option value="Expense">Расход</option><option value="Transfer">Перемещение</option></select><select v-model="filters.financial_article" @change="load"><option value="">Все статьи</option><option v-for="x in options.articles" :key="x.name" :value="x.name">{{x.article_name}}</option></select><button class="filter-reset" @click="reset">↺</button></div>
<div class="table-meta"><strong>{{rows.length}} платежей</strong><span>В отчёты попадают только проведённые операции</span></div><div class="table-shell"><div v-if="loading" class="table-message"><span class="loader"></span></div><div v-else-if="error" class="table-message error-message"><strong>Не удалось загрузить платежи</strong><span>{{error}}</span><button @click="load">Повторить</button></div><div v-else-if="!rows.length" class="table-message"><strong>Платежей пока нет</strong><span>Добавьте операцию вручную или подключите Точка Банк.</span></div><table v-else><thead><tr><th>№</th><th>Дата</th><th>Операция</th><th>Контрагент</th><th>Назначение</th><th>Статья</th><th>Точка</th><th>Сумма</th><th>Статус</th></tr></thead><tbody><tr v-for="row in rows" :key="row.name" @click="open(row.name)"><td class="item-name">{{row.name}}</td><td>{{date(row.posting_date)}}</td><td><span class="type-chip" :class="{income:row.direction==='Income'}">{{row.direction==='Income'?'Приход':row.direction==='Expense'?'Расход':'Перемещение'}}</span></td><td>{{row.counterparty_name||'—'}}</td><td class="finance-purpose">{{row.purpose}}</td><td>{{row.financial_article||'—'}}</td><td>{{row.business_point||'—'}}</td><td class="number-cell" :class="{positive:row.direction==='Income'}">{{row.direction==='Expense'?'−':'+'}}{{money(row.amount)}}</td><td><span class="document-state" :class="`state-${row.docstatus}`">{{row.docstatus===1?'Проведён':row.docstatus===2?'Отменён':'Черновик'}}</span></td></tr></tbody></table></div>
<AppModal v-if="editorOpen" :title="form.name?`Платёж ${form.name}`:'Новый платёж'" wide @close="editorOpen=false"><form class="editor-form" @submit.prevent="save(false)"><div class="form-section"><h3>Операция</h3><div class="form-grid"><label>Тип<select v-model="form.direction" :disabled="form.docstatus!==0" required><option value="Income">Приход</option><option value="Expense">Расход</option><option value="Transfer">Перемещение</option></select></label><label>Дата<input v-model="form.posting_date" type="date" :disabled="form.docstatus!==0" required/></label><label>Сумма<input v-model.number="form.amount" type="number" min="0.01" step="0.01" :disabled="form.docstatus!==0" required/></label><label>ИП<select v-model="form.business_entity" :disabled="form.docstatus!==0" required @change="onEntity"><option value="">Не выбрано</option><option v-for="x in options.entities" :key="x.name" :value="x.name">{{x.short_name}}</option></select></label><label>Точка<select v-model="form.business_point" :disabled="form.docstatus!==0"><option value="">В целом по ИП</option><option v-for="x in pointsFor(form.business_entity)" :key="x.name" :value="x.name">{{x.point_name}}</option></select></label><label>Расчётный счёт<select v-model="form.bank_account" :disabled="form.docstatus!==0"><option value="">Не выбран</option><option v-for="x in accountsFor(form.business_entity)" :key="x.name" :value="x.name">{{x.bank_name}} · {{x.settlement_account}}</option></select></label><label>Статья<select v-model="form.financial_article" :disabled="form.docstatus!==0" required><option value="">Не выбрана</option><option v-for="x in articlesFor(form.direction)" :key="x.name" :value="x.name">{{x.article_name}}</option></select></label><label>Вид потока<select v-model="form.cash_flow_type" :disabled="form.docstatus!==0"><option>Operating</option><option>Investing</option><option>Financing</option><option>Transfer</option></select></label><label>Контрагент<input v-model="form.counterparty_name" :disabled="form.docstatus!==0"/></label><label class="span-3">Назначение<textarea v-model="form.purpose" rows="2" :disabled="form.docstatus!==0" required></textarea></label><label class="span-3">Комментарий<textarea v-model="form.comment" rows="2" :disabled="form.docstatus!==0"></textarea></label></div></div><p v-if="formError" class="form-error">{{formError}}</p></form><template #footer><div><button v-if="form.docstatus===1&&canEdit" class="button button-secondary danger" @click="cancel">Отменить</button></div><div class="footer-actions"><button class="button button-secondary" @click="editorOpen=false">Закрыть</button><button v-if="form.docstatus===0&&canEdit" class="button button-secondary" :disabled="saving" @click="save(false)">Сохранить</button><button v-if="form.docstatus===0&&canEdit" class="button button-primary" :disabled="saving" @click="save(true)">Провести</button></div></template></AppModal></section></template>
