<script setup>
import { computed,onMounted,reactive,ref } from "vue";
import { call,canAccess } from "../api";
import AppModal from "../components/AppModal.vue";
import ListPageHeader from "../components/ListPageHeader.vue";
import SmartFilterBar from "../components/SmartFilterBar.vue";
import SmartDataTable from "../components/SmartDataTable.vue";
const rows=ref([]),loading=ref(true),error=ref(""),editorOpen=ref(false),saving=ref(false),formError=ref("");
const options=reactive({entities:[],points:[],accounts:[],articles:[],payment_methods:[]});
const filters=reactive({from_date:new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),to_date:new Date().toISOString().slice(0,10),business_entity:"",business_point:"",direction:"",financial_article:"",status:"",search:""});
const form=reactive({}); const totals=reactive({income:0,expense:0,net:0});
const canEdit=computed(()=>canAccess("finance.operations","Edit"));
const pointsFor=(entity)=>options.points.filter(row=>!entity||row.business_entity===entity);
const accountsFor=(entity)=>options.accounts.filter(row=>!entity||row.business_entity===entity);
const articlesFor=(direction)=>options.articles.filter(row=>!direction||direction==="Transfer"||row.article_type===(direction==="Income"?"Income":"Expense"));
const money=v=>`${new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₽`;
const date=v=>v?new Intl.DateTimeFormat("ru-RU").format(new Date(`${v}T00:00:00`)):"—";
const directionLabel=value=>value==="Income"?"Приход":value==="Expense"?"Расход":"Перемещение";
const statusLabel=value=>value===1?"Проведён":value===2?"Отменён":"Черновик";
const filterFields=computed(()=>[
  {key:"search",label:"Поиск",placeholder:"Номер, контрагент или назначение",wide:true},{key:"from_date",label:"Период с",type:"date"},{key:"to_date",label:"Период по",type:"date"},
  {key:"business_entity",label:"Юридическое лицо",type:"select",allLabel:"Все ИП",options:options.entities.map(x=>({value:x.name,label:x.short_name}))},
  {key:"business_point",label:"Точка",type:"select",allLabel:"Все точки",options:pointsFor(filters.business_entity).map(x=>({value:x.name,label:x.point_name}))},
  {key:"direction",label:"Операция",type:"select",allLabel:"Все операции",options:[{value:"Income",label:"Приход"},{value:"Expense",label:"Расход"},{value:"Transfer",label:"Перемещение"}]},
  {key:"financial_article",label:"Статья",type:"select",allLabel:"Все статьи",options:options.articles.map(x=>({value:x.name,label:x.article_name}))},
  {key:"status",label:"Статус",type:"select",allLabel:"Все статусы",options:[{value:"0",label:"Черновики"},{value:"1",label:"Проведённые"},{value:"2",label:"Отменённые"}]},
]);
const listColumns=[{key:"name",label:"№",primary:true,width:140},{key:"posting_date",label:"Дата",format:date,width:120},{key:"direction",label:"Операция",format:directionLabel,width:130},{key:"counterparty_name",label:"Контрагент",width:190},{key:"purpose",label:"Назначение",width:280},{key:"financial_article",label:"Статья",width:180},{key:"business_point",label:"Точка",width:170},{key:"amount",label:"Сумма",format:money,number:true,width:140},{key:"docstatus",label:"Статус",format:statusLabel,width:130}];
async function load(){loading.value=true;error.value="";try{const r=await call("raspechatka.api.finance.get_payments",filters);rows.value=r.rows;Object.assign(totals,r.totals);}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function loadOptions(){try{Object.assign(options,await call("raspechatka.api.finance.get_finance_options"));}catch(e){error.value=e.message;}}
async function open(name=null,direction="Expense"){formError.value="";try{const doc=await call("raspechatka.api.finance.get_payment",{name,direction});Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,doc);editorOpen.value=true;}catch(e){error.value=e.message;}}
function onEntity(){if(!pointsFor(form.business_entity).some(x=>x.name===form.business_point))form.business_point="";if(!accountsFor(form.business_entity).some(x=>x.name===form.bank_account))form.bank_account="";}
async function save(submit=false){saving.value=true;formError.value="";try{const r=await call("raspechatka.api.finance.save_payment",{data:JSON.stringify(form),submit:submit?1:0},{method:"POST"});await load();if(submit)editorOpen.value=false;else await open(r.name);}catch(e){formError.value=e.message;}finally{saving.value=false;}}
async function cancel(){if(!confirm("Отменить проведённый платёж?"))return;try{await call("raspechatka.api.finance.cancel_payment",{name:form.name},{method:"POST"});editorOpen.value=false;await load();}catch(e){formError.value=e.message;}}
onMounted(()=>Promise.all([loadOptions(),load()]));
</script>
<template><section class="page finance-page"><ListPageHeader title="Платежи"><template #actions><div v-if="canEdit" class="heading-actions"><button class="button button-secondary" @click="open(null,'Income')">＋ Приход</button><button class="button button-primary" @click="open(null,'Expense')">＋ Расход</button></div></template></ListPageHeader>
<div class="finance-summary"><article><span>ПРИХОД</span><b>{{money(totals.income)}}</b></article><article><span>РАСХОД</span><b>{{money(totals.expense)}}</b></article><article :class="{accent:totals.net>=0}"><span>ДЕНЕЖНЫЙ ПОТОК</span><b>{{money(totals.net)}}</b></article></div>
<SmartFilterBar :model-value="filters" :fields="filterFields" view-key="finance.payments" @update:model-value="Object.assign(filters,$event)" @apply="load" @reset="load" />
<SmartDataTable :rows="rows" :columns="listColumns" :totals="{amount:totals.net}" view-key="finance.payments" :loading="loading" :error="error" empty-title="Платежей пока нет" empty-text="Добавьте операцию вручную или подключите Точка Банк." @open="open($event.name)" @retry="load"><template #cell-direction="{row}"><span class="type-chip" :class="{income:row.direction==='Income'}">{{directionLabel(row.direction)}}</span></template><template #cell-amount="{row}"><span :class="{positive:row.direction==='Income'}">{{row.direction==='Expense'?'−':'+'}}{{money(row.amount)}}</span></template><template #cell-docstatus="{row}"><span class="document-state" :class="`state-${row.docstatus}`">{{statusLabel(row.docstatus)}}</span></template></SmartDataTable>
<AppModal v-if="editorOpen" :title="form.name?`Платёж ${form.name}`:'Новый платёж'" wide @close="editorOpen=false"><form class="editor-form" @submit.prevent="save(false)"><div class="form-section"><h3>Операция</h3><div class="form-grid"><label>Тип<select v-model="form.direction" :disabled="form.docstatus!==0" required><option value="Income">Приход</option><option value="Expense">Расход</option><option value="Transfer">Перемещение</option></select></label><label>Дата<input v-model="form.posting_date" type="date" :disabled="form.docstatus!==0" required/></label><label>Сумма<input v-model.number="form.amount" type="number" min="0.01" step="0.01" :disabled="form.docstatus!==0" required/></label><label>ИП<select v-model="form.business_entity" :disabled="form.docstatus!==0" required @change="onEntity"><option value="">Не выбрано</option><option v-for="x in options.entities" :key="x.name" :value="x.name">{{x.short_name}}</option></select></label><label>Точка<select v-model="form.business_point" :disabled="form.docstatus!==0"><option value="">В целом по ИП</option><option v-for="x in pointsFor(form.business_entity)" :key="x.name" :value="x.name">{{x.point_name}}</option></select></label><label>Расчётный счёт<select v-model="form.bank_account" :disabled="form.docstatus!==0"><option value="">Не выбран</option><option v-for="x in accountsFor(form.business_entity)" :key="x.name" :value="x.name">{{x.bank_name}} · {{x.settlement_account}}</option></select></label><label>Статья<select v-model="form.financial_article" :disabled="form.docstatus!==0" required><option value="">Не выбрана</option><option v-for="x in articlesFor(form.direction)" :key="x.name" :value="x.name">{{x.article_name}}</option></select></label><label>Вид потока<select v-model="form.cash_flow_type" :disabled="form.docstatus!==0"><option>Operating</option><option>Investing</option><option>Financing</option><option>Transfer</option></select></label><label>Контрагент<input v-model="form.counterparty_name" :disabled="form.docstatus!==0"/></label><label class="span-3">Назначение<textarea v-model="form.purpose" rows="2" :disabled="form.docstatus!==0" required></textarea></label><label class="span-3">Комментарий<textarea v-model="form.comment" rows="2" :disabled="form.docstatus!==0"></textarea></label></div></div><p v-if="formError" class="form-error">{{formError}}</p></form><template #footer><div><button v-if="form.docstatus===1&&canEdit" class="button button-secondary danger" @click="cancel">Отменить</button></div><div class="footer-actions"><button class="button button-secondary" @click="editorOpen=false">Закрыть</button><button v-if="form.docstatus===0&&canEdit" class="button button-secondary" :disabled="saving" @click="save(false)">Сохранить</button><button v-if="form.docstatus===0&&canEdit" class="button button-primary" :disabled="saving" @click="save(true)">Провести</button></div></template></AppModal></section></template>
