<script setup>
import { computed,onMounted,reactive,ref } from "vue";
import { call,canAccess } from "../api";
import AppModal from "../components/AppModal.vue";
const month=ref(new Date().toISOString().slice(0,7)),rows=ref([]),loading=ref(true),error=ref(""),open=ref(false),saving=ref(false);const totals=reactive({planned:0,paid:0,remaining:0});const options=reactive({entities:[],points:[],accounts:[],articles:[]});const filters=reactive({business_entity:"",business_point:""});const form=reactive({});
const canEdit=computed(()=>canAccess("finance.planning","Edit"));const money=v=>`${new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₽`;const date=v=>new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short"}).format(new Date(`${v}T00:00:00`));const pointsFor=e=>options.points.filter(x=>!e||x.business_entity===e);const accountsFor=e=>options.accounts.filter(x=>!e||x.business_entity===e);const articlesFor=d=>options.articles.filter(x=>x.article_type===(d==="Income"?"Income":"Expense"));
async function load(){loading.value=true;try{const r=await call("raspechatka.api.finance.get_payment_calendar",{month:`${month.value}-01`,...filters});rows.value=r.rows;Object.assign(totals,r.totals);}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function init(){Object.assign(options,await call("raspechatka.api.finance.get_finance_options"));await load();}
function edit(row=null){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row?JSON.parse(JSON.stringify(row)):{title:"",planned_date:`${month.value}-01`,direction:"Expense",amount:0,currency:"RUB",status:"Planned",business_entity:filters.business_entity||options.entities[0]?.name||"",business_point:filters.business_point||"",recurrence:"Once"});open.value=true;}
async function save(){saving.value=true;try{await call("raspechatka.api.finance.save_plan_item",{data:JSON.stringify(form)},{method:"POST"});open.value=false;await load();}catch(e){error.value=e.message;}finally{saving.value=false;}}
async function remove(){if(!confirm("Удалить плановый платёж?"))return;await call("raspechatka.api.finance.delete_plan_item",{name:form.name},{method:"POST"});open.value=false;await load();}
onMounted(init);
</script>
<template><section class="page finance-page"><div class="page-heading"><div><div class="eyebrow">ФИНАНСЫ / ПЛАНИРОВАНИЕ</div><h1>Платёжный календарь</h1><p>Обязательства, поступления и кассовые разрывы на месяц</p></div><button v-if="canEdit" class="button button-primary" @click="edit()">＋ Запланировать</button></div><div class="finance-summary"><article><span>ВСЕГО К ОПЛАТЕ</span><b>{{money(totals.planned)}}</b></article><article class="accent"><span>ОПЛАЧЕНО</span><b>{{money(totals.paid)}}</b></article><article><span>ОСТАЛОСЬ</span><b>{{money(totals.remaining)}}</b></article></div><div class="finance-toolbar calendar-toolbar"><input v-model="month" type="month" @change="load"/><select v-model="filters.business_entity" @change="filters.business_point='';load()"><option value="">Все ИП</option><option v-for="x in options.entities" :key="x.name" :value="x.name">{{x.short_name}}</option></select><select v-model="filters.business_point" @change="load"><option value="">Все точки</option><option v-for="x in pointsFor(filters.business_entity)" :key="x.name" :value="x.name">{{x.point_name}}</option></select></div><div class="table-shell finance-calendar"><div v-if="loading" class="table-message"><span class="loader"></span></div><div v-else-if="!rows.length" class="table-message"><strong>На этот месяц ничего не запланировано</strong><span>Добавьте регулярные и разовые платежи.</span></div><table v-else><thead><tr><th>Дата</th><th>Платёж</th><th>Контрагент</th><th>Статья</th><th>Точка</th><th>Тип</th><th>Сумма</th><th>Статус</th></tr></thead><tbody><tr v-for="row in rows" :key="row.name" @click="edit(row)"><td class="calendar-date">{{date(row.planned_date)}}</td><td class="item-name">{{row.title}}</td><td>{{row.counterparty_name||'—'}}</td><td>{{row.financial_article}}</td><td>{{row.business_point||'—'}}</td><td>{{row.direction==='Income'?'Поступление':'Оплата'}}</td><td class="number-cell">{{money(row.amount)}}</td><td><span class="document-state" :class="`plan-${row.display_status.toLowerCase()}`">{{row.display_status==='Overdue'?'Просрочено':row.display_status==='Paid'?'Оплачено':row.display_status==='Cancelled'?'Отменено':'Запланировано'}}</span></td></tr></tbody></table></div><p v-if="error" class="form-error">{{error}}</p>
<AppModal v-if="open" :title="form.name?'Плановый платёж':'Новый плановый платёж'" @close="open=false"><form class="editor-form" @submit.prevent="save"><div class="form-section"><div class="form-grid"><label class="span-2">Название<input v-model="form.title" required/></label><label>Дата<input v-model="form.planned_date" type="date" required/></label><label>Тип<select v-model="form.direction"><option value="Expense">Расход</option><option value="Income">Приход</option></select></label><label>Сумма<input v-model.number="form.amount" type="number" min="0.01" step="0.01" required/></label><label>Статус<select v-model="form.status"><option value="Planned">Запланировано</option><option value="Paid">Оплачено</option><option value="Cancelled">Отменено</option></select></label><label>ИП<select v-model="form.business_entity" required><option v-for="x in options.entities" :key="x.name" :value="x.name">{{x.short_name}}</option></select></label><label>Точка<select v-model="form.business_point"><option value="">В целом по ИП</option><option v-for="x in pointsFor(form.business_entity)" :key="x.name" :value="x.name">{{x.point_name}}</option></select></label><label>Статья<select v-model="form.financial_article" required><option v-for="x in articlesFor(form.direction)" :key="x.name" :value="x.name">{{x.article_name}}</option></select></label><label>Контрагент<input v-model="form.counterparty_name"/></label><label>Повторение<select v-model="form.recurrence"><option value="Once">Один раз</option><option value="Monthly">Каждый месяц</option></select></label><label class="span-3">Комментарий<textarea v-model="form.comment"></textarea></label></div></div></form><template #footer><div><button v-if="form.name&&canEdit&&form.status!=='Paid'" class="button button-secondary danger" @click="remove">Удалить</button></div><div class="footer-actions"><button class="button button-secondary" @click="open=false">Закрыть</button><button v-if="canEdit" class="button button-primary" :disabled="saving" @click="save">Сохранить</button></div></template></AppModal></section></template>
