<script setup>
import { computed, onMounted, reactive, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { call } from "../api";
import AppModal from "../components/AppModal.vue";
import ReferenceTable from "../components/ReferenceTable.vue";

const route = useRoute();
const reference = computed(() => route.params.reference);
const rows = ref([]), loading = ref(true), error = ref(""), detail = ref(null), saving = ref(false), formError = ref("");
const search = ref(""), active = ref("");
const form = reactive({}), options = reactive({ entities: [], points: [], positions: [], products: [] });
const supplierBank = reactive({ bank_name: "", bic: "", settlement_account: "", currency: "RUB", active: 1 });
const supplierItem = reactive({ item: "", is_primary: 0, active: 1 });
let timer;

const yesNo = [{ value: 1, label: "Да" }, { value: 0, label: "Нет" }];
const configs = {
  clients: { title: "Клиенты", description: "Единая клиентская база всей сети", create: "Добавить клиента", columns: cols(["client_name","ФИО",1],["phone","Телефон"],["registration_point","Точка регистрации"],["personal_data_consent","Персональные данные"],["marketing_consent","Рассылка"],["active","Статус"]), fields: [f("last_name","Фамилия"),f("first_name","Имя","text",1),f("middle_name","Отчество"),f("phone","Телефон","text",1),f("email","Email","email"),f("registration_point","Точка регистрации","link",1,"points","point_name"),f("personal_data_consent","Согласие на обработку данных","check"),f("marketing_consent","Согласие на рассылку","check"),f("notes","Комментарий","textarea")] },
  suppliers: { title: "Поставщики", description: "Общесетевые и собственные поставщики ИП", create: "Добавить поставщика", columns: cols(["supplier_name","Поставщик",1],["supplier_type","Тип"],["scope","Доступность"],["business_entity","Владелец-ИП"],["inn","ИНН"],["active","Статус"]), fields: [f("supplier_name","Наименование","text",1),f("supplier_type","Тип","select",1,[{value:"Company",label:"Компания"},{value:"Individual Entrepreneur",label:"ИП"},{value:"Individual",label:"Физлицо"}]),f("scope","Доступность","select",1,[{value:"Network",label:"Вся сеть"},{value:"Business Entity",label:"Собственный у ИП"}]),f("business_entity","Владелец-ИП","link",0,"entities","short_name","scope","Business Entity"),f("legal_name","Полное наименование"),f("inn","ИНН"),f("kpp","КПП"),f("ogrn","ОГРН"),f("ogrnip","ОГРНИП"),f("phone","Телефон"),f("email","Email","email"),f("website","Сайт"),f("contact_name","Основное контактное лицо"),f("contact_position","Должность"),f("contact_phone","Телефон контактного лица"),f("contact_email","Email контактного лица","email"),f("notes","Комментарий","textarea")] },
  employees: { title: "Сотрудники", description: "Сотрудники, должности и доступные точки", create: "Добавить сотрудника", columns: cols(["employee_name","ФИО",1],["business_entity","Работодатель"],["position","Должность"],["access_profile","Профиль доступа"],["email","Email"],["active","Статус"]), fields: [f("last_name","Фамилия","text",1),f("first_name","Имя","text",1),f("middle_name","Отчество"),f("phone","Телефон","text",1),f("email","Email","email",1),f("birth_date","Дата рождения","date"),f("business_entity","Работодатель-ИП","link",1,"entities","short_name"),f("position","Должность","link",1,"positions","position_name"),f("access_profile","Профиль доступа","select",1,[{value:"Network Admin",label:"Администратор сети"},{value:"Franchise Owner",label:"Владелец франчайзи"},{value:"Point Manager",label:"Управляющий точками"},{value:"Cashier",label:"Кассир"}]),f("notes","Комментарий","textarea")] },
  positions: { title: "Должности", description: "Единый справочник должностей сети", create: "Добавить должность", columns: cols(["position_name","Должность",1],["description","Описание"],["active","Статус"]), fields: [f("position_name","Должность","text",1),f("description","Описание","textarea")] },
  "catalog-groups": { title: "Группы каталога", description: "Иерархия товаров и услуг", create: "Добавить группу", columns: cols(["group_name","Группа",1],["parent_catalog_group","Родитель"],["is_group","Содержит группы"],["active","Статус"]), fields: [f("group_name","Название","text",1),f("parent_catalog_group","Родительская группа"),f("is_group","Может содержать группы","check")] },
  "catalog-units": { title: "Единицы измерения", description: "Общие единицы измерения сети", create: "Добавить единицу", columns: cols(["unit_name","Единица",1],["symbol","Обозначение"],["allow_fraction","Дробная"],["active","Статус"]), fields: [f("unit_name","Название","text",1),f("symbol","Обозначение","text",1),f("allow_fraction","Разрешить дробное количество","check")] },
  "price-types": { title: "Типы цен", description: "Системные цены продажи и закупки", create: "Добавить тип", columns: cols(["price_type_name","Тип цены",1],["purpose","Назначение"],["currency","Валюта"],["active","Статус"]), fields: [f("price_type_name","Название","text",1),f("purpose","Назначение","select",1,[{value:"Selling",label:"Продажа"},{value:"Buying",label:"Закупка"}]),f("currency","Валюта","text",1)] },
  "financial-articles": { title: "Финансовые статьи", description: "Единые статьи доходов и расходов", create: "Добавить статью", columns: cols(["article_name","Статья",1],["article_type","Тип"],["parent_financial_article","Группа"],["is_group","Это группа"],["active","Статус"]), fields: [f("article_name","Название","text",1),f("article_type","Тип","select",1,[{value:"Income",label:"Доход"},{value:"Expense",label:"Расход"}]),f("parent_financial_article","Родительская статья"),f("is_group","Это группа","check"),f("description","Описание","textarea")] },
  "payment-methods": { title: "Способы оплаты", description: "Системные способы оплаты", columns: cols(["method_name","Способ",1],["method_type","Тип"],["active","Статус"]) },
  "pos-workplaces": { title: "Кассовые рабочие места", description: "По одному рабочему месту на точку", columns: cols(["workplace_name","Рабочее место",1],["business_point","Точка"],["active","Статус"]) },
  "cash-registers": { title: "Кассы", description: "Одна касса наличных на точку", columns: cols(["register_name","Касса",1],["business_point","Точка"],["currency","Валюта"],["active","Статус"]) },
};
function cols(...items){ return items.map(([key,label,primary])=>({key,label,primary:!!primary})); }
function f(key,label,type="text",required=0,values=null,labelKey=null,depends=null,equals=null){ return {key,label,type,required:!!required,values,labelKey,depends,equals}; }
const config = computed(()=>configs[reference.value]);
const visibleFields = computed(()=> (config.value.fields||[]).filter(field=>!field.depends || form[field.depends]===field.equals));
function reset(values={}){ Object.keys(form).forEach(k=>delete form[k]); Object.assign(form,{active:1,...values}); }
function fieldOptions(field){ return Array.isArray(field.values) ? field.values : (options[field.values]||[]).map(v=>({value:v.name,label:v[field.labelKey]})); }
async function load(){ loading.value=true; error.value=""; try{ rows.value=await call("raspechatka.api.references.get_reference_list",{reference:reference.value,search:search.value,active:active.value}); }catch(e){error.value=e.message;}finally{loading.value=false;} }
async function loadOptions(){ try{Object.assign(options,await call("raspechatka.api.references.get_reference_options"));}catch(e){error.value=e.message;} }
function create(){ reset(defaults()); detail.value={}; formError.value=""; }
function defaults(){ if(reference.value==="clients") return {personal_data_consent:0,marketing_consent:0,messengers:[]}; if(reference.value==="suppliers") return {supplier_type:"Company",scope:"Network"}; if(reference.value==="employees") return {access_profile:"Cashier",assigned_points:[]}; if(reference.value==="price-types") return {purpose:"Selling",currency:"RUB"}; return {}; }
async function open(row){ if(!config.value.create)return; try{const data=await call("raspechatka.api.references.get_reference_detail",{reference:reference.value,name:row.name});detail.value=data;reset(JSON.parse(JSON.stringify(data))); if(reference.value==="clients"){for(const m of form.messengers||[]) form[`messenger_${m.messenger_type}`]=m.contact;}}catch(e){error.value=e.message;} }
async function save(){saving.value=true;formError.value="";try{if(reference.value==="clients")form.messengers=["Telegram","WhatsApp","MAX"].filter(t=>form[`messenger_${t}`]).map(t=>({messenger_type:t,contact:form[`messenger_${t}`]}));const r=await call("raspechatka.api.references.save_reference",{reference:reference.value,data:JSON.stringify(form)},{method:"POST"});await Promise.all([load(),loadOptions()]);await open({name:r.name});}catch(e){formError.value=e.message;}finally{saving.value=false;}}
function togglePoint(point){ const list=form.assigned_points||(form.assigned_points=[]); const i=list.findIndex(x=>x.business_point===point.name); if(i>=0)list.splice(i,1);else list.push({business_point:point.name,is_default:list.length?0:1}); }
function hasPoint(name){return (form.assigned_points||[]).some(x=>x.business_point===name);}
async function addBank(){try{await call("raspechatka.api.references.save_supplier_bank_account",{data:JSON.stringify({...supplierBank,supplier:form.name})},{method:"POST"});Object.assign(supplierBank,{bank_name:"",bic:"",settlement_account:"",currency:"RUB",active:1});await open({name:form.name});}catch(e){formError.value=e.message;}}
async function addItem(){try{await call("raspechatka.api.references.save_item_supplier",{data:JSON.stringify({...supplierItem,supplier:form.name})},{method:"POST"});Object.assign(supplierItem,{item:"",is_primary:0,active:1});await open({name:form.name});}catch(e){formError.value=e.message;}}
async function setActive(value){try{await call("raspechatka.api.references.archive_reference",{reference:reference.value,name:form.name,active:value},{method:"POST"});detail.value=null;await load();}catch(e){formError.value=e.message;}}
async function remove(){if(!confirm("Удалить запись без возможности восстановления?"))return;try{await call("raspechatka.api.references.delete_reference",{reference:reference.value,name:form.name},{method:"POST"});detail.value=null;await load();}catch(e){formError.value=e.message;}}
watch(reference,()=>{detail.value=null;search.value="";active.value="";load();});watch(active,load);watch(search,()=>{clearTimeout(timer);timer=setTimeout(load,250);});onMounted(()=>Promise.all([load(),loadOptions()]));
</script>

<template><section class="page reference-page"><div class="page-heading"><div><div class="eyebrow">СПРАВОЧНИКИ</div><h1>{{ config.title }}</h1><p>{{ config.description }}</p></div><button v-if="config.create" class="button button-primary" @click="create">＋ {{ config.create }}</button></div>
<div class="reference-toolbar"><label class="search-field"><span>⌕</span><input v-model="search" placeholder="Поиск по справочнику" /></label><select v-model="active"><option value="">Любой статус</option><option value="1">Активные</option><option value="0">Неактивные</option></select><button class="filter-reset" @click="search='';active=''">↺</button></div>
<ReferenceTable :key="reference" :rows="rows" :columns="config.columns" :view-key="`references.${reference}`" :loading="loading" :error="error" @open="open" @retry="load" />
<AppModal v-if="detail!==null" :title="config.title" wide @close="detail=null"><form class="editor-form" @submit.prevent="save"><div class="form-section"><h3>Основное</h3><div class="form-grid"><label v-for="field in visibleFields" :key="field.key" :class="{'span-3':field.type==='textarea'}">{{ field.label }}<textarea v-if="field.type==='textarea'" v-model="form[field.key]" rows="2"></textarea><select v-else-if="field.type==='select'||field.type==='link'" v-model="form[field.key]" :required="field.required"><option value="">Не выбрано</option><option v-for="o in fieldOptions(field)" :key="o.value" :value="o.value">{{ o.label }}</option></select><input v-else-if="field.type==='check'" v-model="form[field.key]" type="checkbox" :true-value="1" :false-value="0" /><input v-else v-model="form[field.key]" :type="field.type" :required="field.required" /></label><label class="check-field"><input v-model="form.active" type="checkbox" :true-value="1" :false-value="0" /> Активно</label></div></div>
<div v-if="reference==='clients'" class="form-section"><h3>Мессенджеры</h3><div class="form-grid"><label v-for="m in ['Telegram','WhatsApp','MAX']" :key="m">{{m}}<input v-model="form[`messenger_${m}`]" /></label></div></div>
<div v-if="reference==='employees'" class="form-section"><h3>Доступные точки</h3><div class="point-picker"><label v-for="p in options.points.filter(x=>form.access_profile==='Network Admin'||x.business_entity===form.business_entity)" :key="p.name"><input type="checkbox" :checked="hasPoint(p.name)" @change="togglePoint(p)" />{{p.point_name}}</label></div></div>
<template v-if="reference==='suppliers'&&form.name"><div class="form-section"><h3>Банковские счета</h3><div class="compact-list"><div v-for="a in detail.bank_accounts" :key="a.name"><b>{{a.bank_name}}</b><span>{{a.settlement_account}}</span></div></div><div class="inline-form bank-inline"><input v-model="supplierBank.bank_name" placeholder="Банк" /><input v-model="supplierBank.bic" placeholder="БИК" /><input v-model="supplierBank.settlement_account" placeholder="Расчётный счёт" /><button type="button" class="button button-secondary" @click="addBank">Добавить</button></div></div><div class="form-section"><h3>Товары поставщика</h3><div class="compact-list"><div v-for="i in detail.items" :key="i.name"><b>{{i.item}}</b><span>{{i.is_primary?'Основной':'Дополнительный'}}</span></div></div><div class="inline-form"><select v-model="supplierItem.item"><option value="">Выберите товар</option><option v-for="p in options.products" :key="p.name" :value="p.name">{{p.item_name}}</option></select><label class="check-field"><input v-model="supplierItem.is_primary" type="checkbox" :true-value="1" :false-value="0" />Основной</label><button type="button" class="button button-secondary" @click="addItem">Связать</button></div></div></template><p v-if="formError" class="form-error">{{formError}}</p></form>
<template v-if="config.create" #footer><div v-if="form.name" class="danger-actions"><button class="text-button" @click="setActive(form.active?0:1)">{{form.active?'Архивировать':'Восстановить'}}</button><button class="text-button danger" @click="remove">Удалить</button></div><div class="footer-actions"><button class="button button-secondary" @click="detail=null">Отмена</button><button class="button button-primary" :disabled="saving" @click="save">{{saving?'Сохраняем…':'Сохранить'}}</button></div></template></AppModal></section></template>
