<script setup>
import { computed, onMounted, reactive, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { call } from "../api";

const route = useRoute();
const report = computed(() => route.meta.report);
const rows = ref([]), totals = ref({}), loading = ref(true), error = ref(""), settingsOpen = ref(false), selected = ref([]);
const options = reactive({ points: [], warehouses: [], groups: [] });
const filters = reactive({ as_of: new Date().toISOString().slice(0,10), from_date: new Date().toISOString().slice(0,10), to_date: new Date().toISOString().slice(0,10), business_point: "", warehouse: "", catalog_group: "", search: "" });
let timer;
const configs = {
  balances: { title: "Остатки", description: "Фактическое количество и стоимость товаров на выбранную дату" },
  turnover: { title: "Обороты", description: "Приход, расход и изменение запасов за период" },
};
const config = computed(() => configs[report.value]);
const balanceColumns = [c("item_name","Наименование",true),c("item_code","Код"),c("catalog_group","Группа"),c("warehouse_name","Склад"),c("storage_location","Адрес"),c("quantity","Остаток","qty"),c("expected_quantity","Ожидается","qty"),c("uom","Ед."),c("average_rate","Себестоимость","money"),c("stock_value","Стоимость остатка","money")];
const turnoverColumns = [c("item_name","Наименование",true),c("item_code","Код"),c("catalog_group","Группа"),c("warehouse_name","Склад"),c("opening_qty","Начальный остаток","qty"),c("incoming_qty","Приход","qty"),c("outgoing_qty","Расход","qty"),c("closing_qty","Конечный остаток","qty"),c("incoming_value","Приход, ₽","money"),c("outgoing_value","Расход, ₽","money"),c("closing_value","Стоимость остатка","money")];
const columns = computed(() => report.value === "balances" ? balanceColumns : turnoverColumns);
const visibleColumns = computed(() => columns.value.filter((column) => selected.value.includes(column.key)));
const visibleWarehouses = computed(() => options.warehouses.filter((row) => !filters.business_point || row.business_point === filters.business_point));
function c(key,label,primary=false,format=null){return {key,label,primary,format};}
function format(value,column){ if(column.format==="money") return `${new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0))} ₽`; if(column.format==="qty") return new Intl.NumberFormat("ru-RU",{maximumFractionDigits:3}).format(Number(value||0)); return value||"—"; }

async function loadPreference(){ selected.value=columns.value.map((column)=>column.key); try{const p=await call("raspechatka.api.references.get_view_preference",{view_key:`warehouse.${report.value}`});const valid=(p.columns||[]).filter(key=>columns.value.some(column=>column.key===key));if(valid.length)selected.value=valid;}catch(_){} }
async function toggleColumn(key){if(selected.value.includes(key)){if(selected.value.length===1)return;selected.value=selected.value.filter(value=>value!==key);}else selected.value=[...selected.value,key];await call("raspechatka.api.references.save_view_preference",{view_key:`warehouse.${report.value}`,settings:JSON.stringify({columns:selected.value})},{method:"POST"});}
async function load(){loading.value=true;error.value="";try{const common={business_point:filters.business_point,warehouse:filters.warehouse,catalog_group:filters.catalog_group,search:filters.search};const isBalances=report.value==="balances";const method=isBalances?"get_stock_balances":"get_stock_turnover";const params=isBalances?{...common,as_of:filters.as_of}:{...common,from_date:filters.from_date,to_date:filters.to_date};const result=await call(`raspechatka.api.warehouse_reports.${method}`,params);rows.value=result.rows;totals.value=result.totals;}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function loadOptions(){try{Object.assign(options,await call("raspechatka.api.warehouse_reports.get_report_options"));}catch(e){error.value=e.message;}}
function pointChanged(){if(!visibleWarehouses.value.some(row=>row.name===filters.warehouse))filters.warehouse="";load();}
function reset(){filters.business_point="";filters.warehouse="";filters.catalog_group="";filters.search="";load();}
function exportCsv(){const header=visibleColumns.value.map(column=>column.label);const data=rows.value.map(row=>visibleColumns.value.map(column=>row[column.key]??""));const csv=[header,...data].map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${report.value}-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);}
watch(report,()=>{loadPreference();load();});watch(()=>filters.search,()=>{clearTimeout(timer);timer=setTimeout(load,250);});onMounted(()=>Promise.all([loadOptions(),loadPreference(),load()]));
</script>

<template><section class="page report-page"><div class="page-heading"><div><div class="eyebrow">СКЛАД / ОТЧЁТЫ</div><h1>{{config.title}}</h1><p>{{config.description}}</p></div><button class="button button-secondary" @click="exportCsv">Экспорт CSV</button></div>
<div class="report-toolbar"><label class="search-field"><span>⌕</span><input v-model="filters.search" placeholder="Название, код или артикул" /></label><template v-if="report==='balances'"><label class="filter-field">На дату<input v-model="filters.as_of" type="date" @change="load" /></label></template><template v-else><label class="filter-field">С<input v-model="filters.from_date" type="date" @change="load" /></label><label class="filter-field">По<input v-model="filters.to_date" type="date" @change="load" /></label></template><select v-model="filters.business_point" @change="pointChanged"><option value="">Все точки</option><option v-for="point in options.points" :key="point.name" :value="point.name">{{point.point_name}}</option></select><select v-model="filters.warehouse" @change="load"><option value="">Все склады</option><option v-for="warehouse in visibleWarehouses" :key="warehouse.name" :value="warehouse.name">{{warehouse.warehouse_name}}</option></select><select v-model="filters.catalog_group" @change="load"><option value="">Все группы</option><option v-for="group in options.groups" :key="group.name" :value="group.name">{{group.group_name}}</option></select><button class="filter-reset" @click="reset">↺</button></div>
<div class="table-meta"><strong>{{rows.length}} строк</strong><div class="column-settings"><button class="text-button" @click="settingsOpen=!settingsOpen">Настроить столбцы</button><div v-if="settingsOpen" class="column-popover"><label v-for="column in columns" :key="column.key"><input type="checkbox" :checked="selected.includes(column.key)" @change="toggleColumn(column.key)" />{{column.label}}</label></div></div></div>
<div class="table-shell report-table"><div v-if="loading" class="table-message"><span class="loader"></span><span>Рассчитываем отчёт…</span></div><div v-else-if="error" class="table-message error-message"><strong>Не удалось сформировать отчёт</strong><span>{{error}}</span><button @click="load">Повторить</button></div><div v-else-if="!rows.length" class="table-message"><strong>Движений пока нет</strong><span>Проведите складской документ или измените фильтры.</span></div><table v-else><thead><tr><th v-for="column in visibleColumns" :key="column.key">{{column.label}}</th></tr></thead><tbody><tr v-for="(row,index) in rows" :key="`${row.item}-${row.warehouse}-${row.storage_location||index}`"><td v-for="column in visibleColumns" :key="column.key" :class="{'item-name':column.primary,'number-cell':column.format}">{{format(row[column.key],column)}}</td></tr></tbody><tfoot><tr><td v-for="column in visibleColumns" :key="column.key" :class="{'number-cell':column.format}"><strong v-if="column.primary">Итого</strong><strong v-else-if="totals[column.key]!==undefined">{{format(totals[column.key],column)}}</strong></td></tr></tfoot></table></div></section></template>
